'use strict';
// De sex nya maldesignerna mats i en riktig webblasare. jsdom kan inte rakna layout.
const test=require('node:test'),assert=require('node:assert/strict'),path=require('path'),http=require('http'),fs=require('fs');
const ROOT=path.join(__dirname,'..','..'),{startaWebblasare,hoppaOver}=require('../helpers/webblasare.js');
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.json':'application/json','.woff2':'font/woff2'};
const DESIGNS=[['followers','pulse-rail','landscape'],['followers','pulse-tower','portrait'],['likes','signal-ribbon','landscape'],['likes','heart-column','portrait'],['diamonds','prism-core','landscape'],['diamonds','prism-spine','portrait']];
function servera(){const server=http.createServer((req,res)=>{const rel=decodeURIComponent(req.url.split('?')[0]).replace(/^\/+/,''),fil=path.join(ROOT,rel);if(!fil.startsWith(ROOT)||!fs.existsSync(fil)||fs.statSync(fil).isDirectory()){res.writeHead(404);res.end('nej');return}res.writeHead(200,{'content-type':MIME[path.extname(fil)]||'application/octet-stream'});fs.createReadStream(fil).pipe(res)});return new Promise(r=>server.listen(0,'127.0.0.1',()=>r(server)))}
let server,browser,bas,skip=hoppaOver();
test.before(async()=>{if(skip)return;browser=await startaWebblasare();if(!browser)throw new Error('webblasaren kunde inte starta');server=await servera();bas=`http://127.0.0.1:${server.address().port}`});
test.after(async()=>{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r))});
async function mat(kind,model,orientation){const page=await browser.newPage({viewport:{width:1600,height:950}});await page.goto(`${bas}/studio.html?open=layout`,{waitUntil:'load'});await page.waitForFunction(()=>!!document.querySelector('.editor-shell'),null,{timeout:30000,polling:100});await page.waitForTimeout(1200);const matt=await page.evaluate(async({kind,model,orientation})=>{const w=window.VyraWidgets.create(`catalog:socialgoal:${kind}:${model}:${orientation}`);w.x=40;w.y=40;w.goalCurrent=658;state.widgets.length=0;state.widgets.push(w);render();const rot=document.querySelector(`[data-id="${w.id}"]`);if(!rot)return{fel:'widgeten renderades inte'};const art=rot.querySelector('.goal-new-art');if(art&&!art.complete)await new Promise(r=>{art.addEventListener('load',r,{once:true});art.addEventListener('error',r,{once:true})});const box=e=>{const r=e.getBoundingClientRect();return{l:r.left,r:r.right,t:r.top,b:r.bottom,w:r.width,h:r.height}},rb=box(rot),inside=e=>{const b=box(e);return b.l>=rb.l-1&&b.r<=rb.r+1&&b.t>=rb.t-1&&b.b<=rb.b+1};return{klass:rot.className,art:art?.getAttribute('src'),laddad:art?.naturalWidth>0,allaInne:[...rot.querySelectorAll('.goal-new-copy,.goal-new-track,.goal-new-percent')].every(inside),fill:box(rot.querySelector('[data-goal-fill]')),track:box(rot.querySelector('.goal-new-track')),pct:rot.querySelector('[data-goal-pct]')?.textContent,old:!!rot.querySelector('.goal-icon,.goal-track')};},{kind,model,orientation});await page.close();return matt}
for(const [kind,model,orientation] of DESIGNS)test(`${model} renderas komplett som ${orientation}`,{skip},async()=>{const m=await mat(kind,model,orientation);assert.ok(!m.fel,m.fel);assert.match(m.klass,new RegExp(`goal-${model}.*goal-${orientation}`));assert.equal(m.art,`assets/goal-new/${model}.png`);assert.equal(m.laddad,true,'ramasseten laddades inte');assert.equal(m.allaInne,true,'text, progress eller procent klipps');assert.equal(m.pct,'66%');assert.equal(m.old,false,'gammal goal-markup kom tillbaka');if(orientation==='portrait')assert.ok(m.fill.h<m.track.h,'staende progress fylls inte pa hojden');else assert.ok(m.fill.w<m.track.w,'liggande progress fylls inte pa bredden')});
