'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('path'),http=require('http'),fs=require('fs');
const {startaWebblasare,hoppaOver}=require('../helpers/webblasare.js');
const ROOT=path.join(__dirname,'..','..');
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2'};
function serve(){const server=http.createServer((req,res)=>{const rel=decodeURIComponent(req.url.split('?')[0]).replace(/^\/+/,''),file=path.join(ROOT,rel);if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end('nej');return}res.writeHead(200,{'content-type':MIME[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)});return new Promise(resolve=>server.listen(0,'127.0.0.1',()=>resolve(server)))}
let server,browser,base;const skip=hoppaOver();
test.before(async()=>{if(skip)return;browser=await startaWebblasare();server=await serve();base=`http://127.0.0.1:${server.address().port}`});
test.after(async()=>{if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve))});
test('Översikt och Overlay finns kvar efter flera vybyten',{skip,timeout:90000},async()=>{const page=await browser.newPage({viewport:{width:1280,height:900}});try{await page.goto(`${base}/studio.html`,{waitUntil:'load'});await page.waitForFunction(()=>document.documentElement.dataset.ccReady==='1',null,{timeout:20000});await page.waitForSelector('.home-welcome',{timeout:10000});await page.waitForFunction(()=>window.VyraOverlayPreviewReady===true,null,{timeout:20000});await page.click('[data-view="analytics"]');await page.waitForSelector('[data-statistics-page]',{timeout:10000});await page.click('[data-view="overlay"]');await page.waitForSelector('.overlay-widget-gallery',{timeout:10000});await page.click('[data-view="home"]');await page.waitForSelector('.home-welcome',{timeout:10000});const out=await page.evaluate(()=>({home:!!document.querySelector('.home-welcome'),overlayButton:!!document.querySelector('[data-view="overlay"]'),layoutLink:!!document.querySelector('a[href="layout.html"]'),history:!!document.querySelector('[data-alltime]')}));assert.deepEqual(out,{home:true,overlayButton:true,layoutLink:true,history:true})}finally{await page.close()}});
