'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('path'),http=require('http'),fs=require('fs');
const {startaWebblasare,hoppaOver}=require('../helpers/webblasare.js');
const ROOT=path.join(__dirname,'..','..');
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2'};
function servera(){const server=http.createServer((req,res)=>{const rel=decodeURIComponent(req.url.split('?')[0]).replace(/^\/+/,''),file=path.join(ROOT,rel);if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end('nej');return}res.writeHead(200,{'content-type':MIME[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)});return new Promise(resolve=>server.listen(0,'127.0.0.1',()=>resolve(server)))}
let server,browser,base;const skip=hoppaOver();
test.before(async()=>{if(skip)return;browser=await startaWebblasare();server=await servera();base=`http://127.0.0.1:${server.address().port}`});
test.after(async()=>{if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve))});
test('Statistik hämtar och visar riktiga totalsiffror, dagar och toppsupportrar',{skip,timeout:90000},async()=>{const page=await browser.newPage({viewport:{width:1280,height:900}});try{await page.goto(`${base}/studio.html`,{waitUntil:'load'});await page.waitForFunction(()=>document.documentElement.dataset.ccReady==='1',null,{timeout:20000});await page.evaluate(()=>{window.__statsPaths=[];window.VyraCloudSync={current:()=>({workspace:{id:'ws-live'}})};window.VyraAuth={api:async path=>{window.__statsPaths.push(path);return{period:'30d',fran:'2026-08-21',forstaDagen:'2026-09-01',konto:'creator',fel:false,totalt:{gifts:12,diamonds:3450,likes:6789},dagar:[{dag:'2026-09-01',gifts:4,diamonds:1200,likes:2000},{dag:'2026-09-02',gifts:8,diamonds:2250,likes:4789}],toppGivare:[{id:'maya',namn:'Maya',avatar:'',gifts:8,diamonds:2250,likes:50,bastaGava:{namn:'Lion',diamanter:2000}}]}}};view='analytics';render()});await page.waitForFunction(()=>document.querySelector('[data-stats-total="diamonds"]')?.textContent.includes('3'),null,{timeout:10000});const out=await page.evaluate(()=>({totals:[...document.querySelectorAll('[data-stats-total]')].map(x=>x.textContent),bars:document.querySelectorAll('.statistics-bar').length,supporters:document.querySelector('[data-stats-supporters]')?.textContent||'',paths:window.__statsPaths}));assert.deepEqual(out.totals.map(x=>x.replace(/\D/g,'')),['12','3450','6789']);assert.equal(out.bars,2);assert.match(out.supporters,/Maya/);assert.match(out.supporters,/Lion/);assert.ok(out.paths.some(p=>/\/api\/workspaces\/ws-live\/stats\?period=30d/.test(p)),JSON.stringify(out.paths))}finally{await page.close()}});
