(() => {
  const seen=new Set(),queue=[];let busy=false;
  const fill=(text='',p={})=>text.replace(/\{(\w+)\}/g,(_,k)=>({username:p.username||p.user||'TestUser',giftname:p.giftname||p.gift||'Rose',repeatcount:p.repeatcount||p.combo||1,coins:p.coins||0,likecount:p.likecount||p.likes||0,totallikecount:p.totallikecount||p.totalLikes||0,comment:p.comment||'',submonth:p.submonth||1}[k]??''));
  function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open('vyra-action-media',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('files'))r.result.createObjectStore('files')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
  async function file(meta){if(!meta?.id)return null;const db=await openDb(),value=await new Promise((ok,no)=>{const tx=db.transaction('files');const r=tx.objectStore('files').get(meta.id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});db.close();return value}
  function allowed(action){const scene=window.VYRA_OVERLAY_SCENE;return !!scene&&Number(action.scene?.number||1)===Number(scene)}
  function stage(action){let host=document.querySelector('#vyraActionRuntime');if(!host){host=document.createElement('div');host.id='vyraActionRuntime';document.body.append(host)}const scene=action.scene||{},el=document.createElement('div');el.className=`vyra-runtime-item ${action.fade?'fade':''}`;el.style.cssText=`--x:${scene.x??160};--y:${scene.y??1450};--w:${scene.width??760};--z:${scene.layer??10}`;host.append(el);requestAnimationFrame(()=>el.classList.add('active'));const ms=Math.max(1,action.duration||6)*1000;setTimeout(()=>el.classList.remove('active'),ms-350);setTimeout(()=>el.remove(),ms);return el}
  async function playMedia(action,kind,meta){const blob=await file(meta);if(!blob)return;const url=URL.createObjectURL(blob);if(kind==='audio'){const audio=new Audio(url);audio.volume=(action.volume??80)/100;audio.onended=()=>URL.revokeObjectURL(url);await audio.play().catch(()=>window.toast?.('Webbläsaren blockerade ljudet'));return}const el=stage(action),media=document.createElement(kind==='video'?'video':'img');media.src=url;if(kind==='video'){media.autoplay=true;media.playsInline=true;media.volume=(action.volume??80)/100;media.onended=()=>el.remove()}media.onload=media.onloadeddata=()=>el.classList.add('loaded');el.append(media);setTimeout(()=>URL.revokeObjectURL(url),Math.max(2,action.duration||6)*1000+1000)}
  function tts(action,payload){const c=action.config||{},text=fill(c.ttsText,payload);if(!text||!window.speechSynthesis)return;const u=new SpeechSynthesisUtterance(text),voices=speechSynthesis.getVoices();u.rate=c.speed||1;u.pitch=c.pitch||1;u.volume=(action.volume??80)/100;if(voices.length){if(c.randomVoice)u.voice=voices[Math.floor(Math.random()*voices.length)];else if(c.voice)u.voice=voices.find(v=>v.name===c.voice||v.lang===c.voice)||null}speechSynthesis.speak(u)}
  function runWidget(action,payload){const name=String(action.config?.widget||'').toLowerCase();if(name.includes('firework'))return window.triggerGiftFireworks?.(payload.combo||payload.repeatcount||1);if(name.includes('follower'))return window.triggerNewFollower?.(payload);if(name.includes('top like'))return window.triggerLikeFountainPop?.(payload);if(name.includes('battle mvp'))return window.triggerBattleMvp?.(payload);if(name.includes('level'))return window.triggerGifterLevelUp?.(payload);const aliases={'gift campaign':'campaign','heart me goal':'goal'},needle=aliases[name]||name;let widget=window.state?.widgets?.find(w=>String(w.type+' '+(w.title||'')).toLowerCase().includes(needle));let el=widget&&document.querySelector(`[data-id="${CSS.escape(String(widget.id))}"]`);if(el){el.classList.remove('vyra-action-widget-active');void el.offsetWidth;el.classList.add('vyra-action-widget-active');setTimeout(()=>el.classList.remove('vyra-action-widget-active'),Math.max(1,Number(action.duration)||6)*1000);return true}document.dispatchEvent(new CustomEvent('vyra:runtime-widget',{detail:{action,payload}}));return false}
  async function executeNow(detail){const {action,payload={}}=detail,types=action.types||[],c=action.config||{};if(types.includes('picture'))playMedia(action,'picture',action.pictureMedia);if(types.includes('video'))playMedia(action,'video',action.videoMedia);if(types.includes('audio'))playMedia(action,'audio',action.audioMedia);if(types.includes('alert'))document.dispatchEvent(new CustomEvent('vyra:runtime-alert',{detail:{action,payload}}));if(types.includes('tts'))tts(action,payload);if(types.includes('overlay')||types.includes('animation'))runWidget(action,payload);if(types.includes('chat'))document.dispatchEvent(new CustomEvent('vyra:chatbot-send',{detail:{message:fill(c.chatText,payload),action,payload}}));if(types.includes('spotify'))document.dispatchEvent(new CustomEvent('vyra:spotify-play',{detail:{query:c.spotify,action,payload}}));if(types.includes('obsScene'))document.dispatchEvent(new CustomEvent('vyra:obs-scene',{detail:{scene:c.obsScene,action}}));if(types.includes('obsSource'))document.dispatchEvent(new CustomEvent('vyra:obs-source',{detail:{source:c.obsSource,action}}));if(types.includes('webhook')&&c.webhook)fetch(c.webhook,{method:'POST',mode:'no-cors',body:JSON.stringify(payload)}).catch(()=>window.toast?.('Webhook kunde inte nås'))}
  function next(){if(busy||!queue.length)return;busy=true;const detail=queue.shift();executeNow(detail).finally(()=>setTimeout(()=>{busy=false;next()},Math.max(1,Number(detail.action.duration)||6)*1000))}
  function execute(detail){if(!detail?.action||seen.has(detail.runId)||!allowed(detail.action))return false;seen.add(detail.runId);setTimeout(()=>seen.delete(detail.runId),15000);queue.push(detail);next();return true}
  document.addEventListener('vyra:action',e=>execute(e.detail));addEventListener('storage',e=>{if(e.key==='vyra-action-run'&&e.newValue)try{execute(JSON.parse(e.newValue))}catch{}});window.VyraActionRuntime={execute,queueSize:()=>queue.length+(busy?1:0),clearQueue:()=>queue.splice(0)};
})();
