(() => {
  const KEY='vyra-action-event-v2';
  const actionTypes=[['overlay','Visa overlay/widget'],['animation','Visa animation'],['picture','Visa bild/GIF'],['audio','Spela ljud'],['video','Spela video'],['alert','Visa alert'],['tts','Läs text (TTS)'],['chat','Skicka chatbotmeddelande'],['spotify','Spela Spotify'],['obsScene','Byt OBS-scen'],['obsSource','Aktivera OBS-källa'],['webhook','Anropa webhook']];
  const triggerNames={gift:'Gåva mottagen',giftCombo:'Gift-combo',follow:'Ny följare',member:'Ny medlem',likes:'Likes uppnådda',share:'Delning',level:'Level up',battle:'Battle-event',chat:'Chattkommando',join:'Går med i liven',firstActivity:'Första aktiviteten',chatCommand:'Chattkommando',giftCoins:'Minsta coin-värde',subscriberEmote:'Subscriber-emote',fanSticker:'Fan Club-sticker',shopPurchase:'TikTok Shop-köp'};
  const read=()=>JSON.parse(localStorage.getItem(KEY)||'{"actions":[],"events":[]}');
  const write=state=>localStorage.setItem(KEY,JSON.stringify(state));
  const name=(state,id)=>state.actions.find(a=>a.id===id)?.name||'Action saknas';
  const eventActionNames=(state,event)=>{const ids=event.allActionIds?.length?event.allActionIds:event.randomActionIds?.length?event.randomActionIds:[event.actionId];return ids.map(id=>name(state,id)).join(', ')};
  function persist(state){write(state);renderPage()}
  function sceneOnline(number){return Date.now()-Number(localStorage.getItem(`vyra-scene-heartbeat-${number}`)||0)<6000}
  function shell(){const state=read();return `<div class="ae-head"><div><h2>Action & Event</h2><p>Skapa en Action först. Koppla sedan ett Event som triggar den.</p></div><div><button id="newAeAction" class="primary">＋ Ny Action</button><button id="newAeEvent">＋ Nytt Event</button></div></div><div class="ae-steps"><b>1</b><span>Skapa Action</span><i>→</i><b>2</b><span>Koppla Event</span><i>→</i><b>3</b><span>Trigger kör Action</span></div><div class="ae-columns"><section class="card"><header><h3>Actions</h3><span>${state.actions.length} sparade</span></header><div class="ae-list">${state.actions.length?state.actions.map(a=>{const n=a.scene?.number||1,on=sceneOnline(n);return `<article><i>⚡</i><span><b>${a.name}</b><small>${a.types.map(t=>actionTypes.find(x=>x[0]===t)?.[1]||t).join(' · ')} · Scen ${n} <mark class="ae-action-scene ${on?'online':'offline'}">${on?'Online':'Offline'}</mark></small></span><em>${a.duration}s</em><button data-test-action="${a.id}">Testa</button><button data-delete-action="${a.id}">×</button></article>`}).join(''):'<p>Inga Actions ännu. Skapa den första.</p>'}</div></section><section class="card"><header><h3>Events</h3><span>${state.events.length} kopplingar</span></header><div class="ae-list">${state.events.length?state.events.map(e=>`<article class="${e.enabled?'':'off'}"><i>◇</i><span><b>${triggerNames[e.advancedTrigger||e.trigger]||e.advancedTrigger||e.trigger}</b><small>→ ${eventActionNames(state,e)}</small></span><button data-toggle-event="${e.id}">${e.enabled?'Aktiv':'Pausad'}</button><button data-test-event="${e.id}">Testa</button><button data-delete-event="${e.id}">×</button></article>`).join(''):'<p>Inga Events ännu. Koppla ett event till en Action.</p>'}</div></section></div><div id="aeModal"></div>`}
  function renderPage(){if(!document.querySelector('[data-extra="actions"]')?.classList.contains('active'))return;document.querySelector('#title').textContent='Action & Event';document.querySelector('#view').innerHTML=shell();bindPage()}
  function bindClose(){document.querySelectorAll('[data-close-ae]').forEach(x=>x.onclick=()=>document.querySelector('#aeModal').innerHTML='')}
  function actionModal(){document.querySelector('#aeModal').innerHTML=`<div class="ae-modal"><div><header><h3>Ny Action</h3><button data-close-ae>×</button></header><label>Actionens namn<input id="aeActionName" placeholder="Exempel: Gift Fireworks combo"></label><fieldset><legend>Vad ska hända? Flera val är möjliga.</legend>${actionTypes.map(x=>`<label><input type="checkbox" value="${x[0]}"> ${x[1]}</label>`).join('')}</fieldset><div class="ae-grid"><label>Visningstid<input id="aeDuration" type="number" min="1" max="60" value="6"></label><label>Global cooldown<input id="aeCooldown" type="number" min="0" max="300" value="2"></label><label>Volym<input id="aeVolume" type="range" min="0" max="100" value="80"></label><label><input id="aeFade" type="checkbox" checked> Fade in/ut</label><label><input id="aeRepeatCombo" type="checkbox"> Upprepa med gift-combo</label></div><footer><button data-close-ae>Avbryt</button><button id="saveAeAction" class="primary">Spara Action</button></footer></div></div>`;bindClose();document.querySelector('#saveAeAction').onclick=()=>{const m=document.querySelector('.ae-modal'),actionName=m.querySelector('#aeActionName').value.trim(),types=[...m.querySelectorAll('fieldset input:checked')].map(x=>x.value);if(!actionName||!types.length)return window.toast?.('Ange namn och välj minst en funktion');const state=read();state.actions.push({id:'a'+Date.now(),name:actionName,types,duration:+m.querySelector('#aeDuration').value,cooldown:+m.querySelector('#aeCooldown').value,volume:+m.querySelector('#aeVolume').value,fade:m.querySelector('#aeFade').checked,repeatCombo:m.querySelector('#aeRepeatCombo').checked});persist(state);window.toast?.('Action sparad')}}
  function eventModal(){const state=read();if(!state.actions.length)return window.toast?.('Skapa en Action först');document.querySelector('#aeModal').innerHTML=`<div class="ae-modal"><div><header><h3>Nytt Event</h3><button data-close-ae>×</button></header><label>När detta händer<select id="aeTrigger">${Object.entries(triggerNames).slice(0,9).map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label><label>Värde / villkor<input id="aeCondition" placeholder="Exempel: Rose, 10000 eller !hype"></label><label>Kör denna Action<select id="aeActionId">${state.actions.map(a=>`<option value="${a.id}">${a.name}</option>`).join('')}</select></label><footer><button data-close-ae>Avbryt</button><button id="saveAeEvent" class="primary">Spara Event</button></footer></div></div>`;bindClose();document.querySelector('#saveAeEvent').onclick=()=>{const current=read();current.events.push({id:'e'+Date.now(),trigger:document.querySelector('#aeTrigger').value,condition:document.querySelector('#aeCondition').value.trim(),actionId:document.querySelector('#aeActionId').value,enabled:true});persist(current);window.toast?.('Event kopplat till Action')}}
  function runAction(action,payload={}){if(!action)return false;const state=read(),stored=state.actions.find(a=>a.id===action.id)||action,scene=stored.scene?.number||1,now=Date.now();if(!window.VYRA_OVERLAY_SCENE&&!sceneOnline(scene)){window.toast?.(`Scen ${scene} är offline. Öppna scenlänken först.`);document.querySelector(`[data-scene-link="${scene}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});return false}if(stored.lastRun&&now-stored.lastRun<(stored.cooldown||0)*1000){window.toast?.('Action väntar på cooldown');return false}stored.lastRun=now;if(!state.actions.some(a=>a.id===stored.id))state.actions.push(stored);write(state);const detail={action:stored,payload,runId:'run-'+now+'-'+Math.random().toString(36).slice(2)};if(window.VYRA_OVERLAY_SCENE)document.dispatchEvent(new CustomEvent('vyra:action',{detail}));try{localStorage.setItem('vyra-action-run',JSON.stringify({...detail,at:now}))}catch{}window.toast?.(`Kör ${stored.name} på Scen ${scene}`);return true}
  function actionsForEvent(state,event){if(event.allActionIds?.length)return event.allActionIds;if(event.randomActionIds?.length)return[event.randomActionIds[Math.floor(Math.random()*event.randomActionIds.length)]];return[event.actionId]}
  function runEvent(event,payload={}){const state=read();if(!event?.enabled&&payload.__test!==true)return false;actionsForEvent(state,event).forEach(id=>runAction(state.actions.find(a=>a.id===id),payload));return true}
  function handleEvent(trigger,payload={}){if(window.VyraAdvancedEvents)return window.VyraAdvancedEvents.handleEvent(trigger,payload);const state=read();state.events.filter(e=>e.enabled&&(e.advancedTrigger||e.trigger)===trigger).forEach(e=>{const condition=e.triggerValue||e.condition;if(!condition||String(payload.value??payload.gift??payload.command??'').toLowerCase().includes(String(condition).toLowerCase()))runEvent(e,payload)})}
  function bindPage(){document.querySelector('#newAeAction').onclick=actionModal;document.querySelector('#newAeEvent').onclick=eventModal;document.querySelectorAll('[data-delete-action]').forEach(b=>b.onclick=()=>{const state=read(),id=b.dataset.deleteAction;state.actions=state.actions.filter(a=>a.id!==id);state.events=state.events.map(e=>({...e,allActionIds:(e.allActionIds||[]).filter(x=>x!==id),randomActionIds:(e.randomActionIds||[]).filter(x=>x!==id)})).filter(e=>e.actionId!==id||e.allActionIds.length||e.randomActionIds.length);persist(state)});document.querySelectorAll('[data-delete-event]').forEach(b=>b.onclick=()=>{const state=read();state.events=state.events.filter(e=>e.id!==b.dataset.deleteEvent);persist(state)});document.querySelectorAll('[data-toggle-event]').forEach(b=>b.onclick=()=>{const state=read(),e=state.events.find(x=>x.id===b.dataset.toggleEvent);if(e)e.enabled=!e.enabled;persist(state)});document.querySelectorAll('[data-test-action]').forEach(b=>b.onclick=()=>{const state=read();runAction(state.actions.find(a=>a.id===b.dataset.testAction),{username:'TestUser',giftname:'Rose',gift:'Rose',profileImage:'assets/images/test-profile.svg',combo:5,repeatcount:5,coins:5,__test:true})});document.querySelectorAll('[data-test-event]').forEach(b=>b.onclick=()=>{const state=read(),e=state.events.find(x=>x.id===b.dataset.testEvent);runEvent(e,{username:'TestUser',giftname:e.triggerValue||'Rose',gift:e.triggerValue||'Rose',command:e.triggerValue||'!test',value:e.triggerValue||'',profileImage:'assets/images/test-profile.svg',combo:5,repeatcount:5,coins:5,teamLevel:50,isFollower:true,isSubscriber:true,isModerator:true,isTopGifter:true,__test:true});window.toast?.('Event testat → '+eventActionNames(state,e))})}
  document.addEventListener('click',e=>{if(e.target.closest('[data-extra="actions"]'))setTimeout(renderPage,0)},true);
  window.VyraActionEvent={handleEvent,runAction,runEvent,refresh:renderPage,read};
})();
