(function(root){
  'use strict';
  let required=false,current=null,lastDetail=null,mode='login';
  async function api(path,options={}){const csrf=sessionStorage.getItem('vyra-csrf');const r=await fetch(path,{credentials:'include',headers:{'Content-Type':'application/json',...(csrf?{'X-VYRA-CSRF':csrf}:{}),...(options.headers||{})},...options});const d=await r.json().catch(()=>({ok:false,error:'Serverfel'}));if(!r.ok)throw Object.assign(new Error(d.error||'Serverfel'),{status:r.status});return d}
  function shell(){document.querySelector('.auth-gate')?.remove();const gate=document.createElement('div');gate.className='auth-gate';gate.innerHTML=`<section><div class="auth-brand"><i>V</i><b>VYRA</b></div><header><h1>${mode==='login'?'Välkommen tillbaka':'Skapa ditt VYRA-konto'}</h1><p>${mode==='login'?'Logga in för att öppna ditt workspace.':'Din första säkra workspace skapas automatiskt.'}</p></header><form><label>E-post<input id="authEmail" type="email" autocomplete="email" maxlength="254" required></label><label>Lösenord<input id="authPassword" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" minlength="12" maxlength="128" required></label>${mode==='register'?'<label>Visningsnamn<input id="authName" maxlength="80" required></label>':''}<p id="authError" role="alert"></p><button class="primary" type="submit">${mode==='login'?'Logga in':'Skapa konto'}</button></form><button id="authSwitch">${mode==='login'?'Saknar du konto? Skapa ett':'Har du redan konto? Logga in'}</button><small>Säkra HttpOnly-sessioner · lösenordet sparas aldrig i webbläsaren</small></section>`;document.body.append(gate);gate.querySelector('#authSwitch').onclick=()=>{mode=mode==='login'?'register':'login';shell()};gate.querySelector('form').onsubmit=submit}
  async function finish(d){if(!d.workspaces){const me=await api('/api/auth/me');if(me.csrfToken)sessionStorage.setItem('vyra-csrf',me.csrfToken);d={...d,...me}}current=d.user;lastDetail=d;document.querySelector('.auth-gate')?.remove();root.dispatchEvent(new CustomEvent('vyra-auth-ready',{detail:d}));root.toast?.('Inloggad som '+(d.user.display_name||d.user.displayName||d.user.email))}
  function mfaShell(d){const gate=document.querySelector('.auth-gate');gate.innerHTML='<section><div class="auth-brand"><i>V</i><b>VYRA</b></div><header><h1>Tvåstegsverifiering</h1><p>Ange den sexsiffriga koden från din autentiseringsapp eller en återställningskod.</p></header><form><label>Säkerhetskod<input id="authMfaCode" inputmode="numeric" autocomplete="one-time-code" maxlength="12" required autofocus></label><p id="authError" role="alert"></p><button class="primary">Bekräfta</button></form><button id="authCancel">Avbryt och logga ut</button><small>En återställningskod kan bara användas en gång.</small></section>';gate.querySelector('#authCancel').onclick=logout;gate.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button'),error=gate.querySelector('#authError');button.disabled=true;error.textContent='';try{const out=await api('/api/auth/mfa/challenge',{method:'POST',body:JSON.stringify({code:gate.querySelector('#authMfaCode').value})});if(out.recoveryCodeUsed)root.toast?.('Återställningskoden är nu förbrukad');await finish(d)}catch(err){error.textContent=err.message;button.disabled=false}}}
  async function submit(e){e.preventDefault();const form=e.currentTarget,button=form.querySelector('button'),error=form.querySelector('#authError'),payload={email:form.querySelector('#authEmail').value,password:form.querySelector('#authPassword').value};if(mode==='register')payload.displayName=form.querySelector('#authName').value;button.disabled=true;error.textContent='';try{const d=await api('/api/auth/'+mode,{method:'POST',body:JSON.stringify(payload)});sessionStorage.setItem('vyra-csrf',d.csrfToken);if(d.mfaRequired)return mfaShell(d);await finish(d)}catch(err){error.textContent=err.message;button.disabled=false}}
  async function init(){const params=new URLSearchParams(location.search);if(params.has('access')||params.has('verify-email')||params.has('reset-password'))return;try{const config=await api('/api/auth/config');required=!!config.authRequired;if(!required)return;try{const d=await api('/api/auth/me');if(d.csrfToken)sessionStorage.setItem('vyra-csrf',d.csrfToken);current=d.user;lastDetail=d;root.dispatchEvent(new CustomEvent('vyra-auth-ready',{detail:d}))}catch{shell()}}catch{required=false}}
  async function logout(){try{await api('/api/auth/logout',{method:'POST',body:'{}'})}finally{sessionStorage.removeItem('vyra-csrf');current=null;if(required)shell()}}
  root.VyraAuth={init,logout,api,isRequired:()=>required,currentUser:()=>current,lastDetail:()=>lastDetail,showGate:(m='login')=>{mode=m;shell()}};init();
})(typeof window!=='undefined'?window:globalThis);
