(function(root){
  'use strict';
  function modal(){let el=document.querySelector('.billing-modal');if(el)return el;el=document.createElement('div');el.className='billing-modal';el.innerHTML='<section><button class="billing-close">×</button><small>VYRA PREMIUM</small><h2>Allt du behöver för din LIVE</h2><div class="billing-price"><b>$15</b><span>USD / månad</span></div><strong>3 dagar gratis</strong><p>Efter provperioden förnyas Premium automatiskt för 15 USD varje månad. Du kan säga upp när som helst direkt här.</p><ul><li>Alla premiumwidgets och designer</li><li>Upp till 50 overlays och 500 widgets</li><li>50 GB säker medialagring</li><li>Realtid, cloud-synk och säkra OBS-länkar</li></ul><div class="billing-actions"><button class="primary billing-start">Starta 3 dagar gratis</button><button class="billing-manage">Fakturor & betalmetod</button><button class="billing-cancel">Säg upp abonnemang</button></div><div class="billing-undo"><button class="billing-resume">Ångra uppsägningen</button></div><p class="billing-state"></p></section>';document.body.append(el);el.querySelector('.billing-close').onclick=()=>el.remove();return el}
  async function open(){const current=root.VyraCloudSync?.current?.(),workspace=current?.workspace;if(!workspace)return root.toast?.('Vänta tills cloud-synken är ansluten');const el=modal(),base=`/api/workspaces/${workspace.id}/billing`,state=el.querySelector('.billing-state'),visaFel=fel=>{state.textContent=fel&&fel.message||'Något gick fel';state.classList.add('billing-fel')},cancel=el.querySelector('.billing-cancel'),resume=el.querySelector('.billing-resume');async function refresh(){try{const info=await root.VyraAuth.api(base),active=info.plan==='premium',ending=!!info.subscription?.cancel_at_period_end,date=info.subscription?.current_period_end?new Date(info.subscription.current_period_end).toLocaleDateString('sv-SE'):'';state.classList.remove('billing-fel');state.textContent=!active?'Inget aktivt abonnemang':ending?`Uppsagt · Premium fungerar till ${date}`:info.subscription?.status==='trialing'?'Premium · gratis provperiod · förnyas automatiskt för 15 USD/månad':'Premium · förnyas automatiskt för 15 USD/månad';el.querySelector('.billing-start').hidden=active;cancel.hidden=!active||ending;resume.hidden=!active||!ending;el.querySelector('.billing-manage').hidden=!active}catch(error){visaFel(error)}}el.querySelector('.billing-start').onclick=async()=>{try{state.textContent='Öppnar säker betalning…';const result=await root.VyraAuth.api(base+'/checkout',{method:'POST',body:'{}'});location.href=result.url}catch(error){visaFel(error)}};el.querySelector('.billing-manage').onclick=async()=>{try{const result=await root.VyraAuth.api(base+'/portal',{method:'POST',body:'{}'});location.href=result.url}catch(error){visaFel(error)}};cancel.onclick=async()=>{if(!confirm('Säg upp VYRA Premium? Du behåller åtkomsten till slutet av perioden och inga fler månadsbetalningar görs.'))return;try{await root.VyraAuth.api(base+'/cancel',{method:'POST',body:'{}'});await refresh()}catch(error){visaFel(error)}};resume.onclick=async()=>{if(!confirm('Ångra uppsägningen? Premium fortsätter då som vanligt och 15 USD dras vid nästa förnyelse.'))return;try{await root.VyraAuth.api(base+'/resume',{method:'POST',body:'{}'});await refresh()}catch(error){visaFel(error)}};refresh()}
  // API:t har ALDRIG exporterats. vyra-trial-onboarding.js och inställningarnas rad anropar
  // `window.VyraBilling.open()` med en reserv som klickar den dolda `.billing-open` — och det var
  // reserven som bar allt, medan huvudvägen tyst var undefined. Ett anrop som alltid faller
  // igenom till en reserv är en reserv utan huvudväg.
  root.VyraBilling = Object.assign(root.VyraBilling || {}, { open });

  function mount(){if(new URLSearchParams(location.search).has('access')||document.querySelector('.billing-open'))return;const button=document.createElement('button');button.className='billing-open';button.hidden=true;button.onclick=open;document.body.append(button)}
  if(document.readyState==='loading')addEventListener('DOMContentLoaded',mount);else mount();setTimeout(mount,1000);
})(typeof window!=='undefined'?window:globalThis);
