(function(root){
  'use strict';
  const META='vyra-cloud-sync-meta',QUEUE='vyra-cloud-sync-queue',EXTRA=['vyra-extras','vyra-action-event-v2','vyra-favorite-widgets','vyra-wishlist','vyra-overlay-resolution'];
  let workspace=null,overlay=null,lastLocal=localStorage.getItem('vyra-state'),timer=null,syncing=false,status='local',initialized=false;
  function read(key,fallback=null){try{return JSON.parse(localStorage.getItem(key))}catch{return fallback}}
  function payload(){const state=read('vyra-state');if(!state||!Array.isArray(state.widgets))return null;const storage={};EXTRA.forEach(k=>{const v=localStorage.getItem(k);if(v!=null)storage[k]=v});return{...state,__vyraCloud:{schema:1,storage,savedAt:Date.now()}}}
  function apply(remote){if(!remote||!Array.isArray(remote.widgets))throw new Error('Online-layouten är ogiltig');const data={...remote},meta=data.__vyraCloud;delete data.__vyraCloud;localStorage.setItem('vyra-state',JSON.stringify(data));Object.entries(meta?.storage||{}).forEach(([k,v])=>{if(EXTRA.includes(k)&&typeof v==='string')localStorage.setItem(k,v)});if(typeof state==='object'&&state){Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,data)}lastLocal=localStorage.getItem('vyra-state');root.render?.()}
  function setStatus(next,text){status=next;document.querySelectorAll('.cloud-status').forEach(el=>{el.dataset.state=next;el.querySelector('span').textContent=text||({synced:'Sparad online',saving:'Sparar…',offline:'Offline · sparas senare',conflict:'Synkkonflikt',local:'Lokalt läge'}[next])})}
  function mountStatus(){}
  async function call(path,options){return root.VyraAuth.api(path,options)}
  async function list(){return call(`/api/workspaces/${workspace.id}/overlays`)}
  async function create(){const data=payload();const d=await call(`/api/workspaces/${workspace.id}/overlays`,{method:'POST',body:JSON.stringify({name:'Min VYRA-overlay',state:data})});overlay=d.overlay;saveMeta();return overlay}
  function saveMeta(){if(!overlay)return;localStorage.setItem(META,JSON.stringify({workspaceId:workspace.id,overlayId:overlay.id,version:overlay.version,updatedAt:overlay.updated_at,lastLocal}))}
  async function getRemote(id){return(await call(`/api/workspaces/${workspace.id}/overlays/${id}`)).overlay}
  // Wipe-guard: allowEmptyWidgets följer med bara när användaren själv raderat sista widgeten
  // i den här sessionen (flaggas av layer-delete i media.js). En tom layout från t.ex. en
  // nyinloggad enhet utan lokal historik stoppas annars av serverns 409 emptyBlocked och
  // hamnar i den vanliga konfliktdialogen istället för att tyst nolla molnet.
  async function push(){if(!workspace||!overlay||syncing)return{ok:false,status:0,reason:'busy'};const data=payload();if(!data)return{ok:false,status:0,reason:'no-state'};syncing=true;setStatus('saving');try{const emptied=root.__vyraUserEmptiedWidgets===true;let d;try{d=await call(`/api/workspaces/${workspace.id}/overlays/${overlay.id}`,{method:'PUT',body:JSON.stringify({name:overlay.name,state:data,version:overlay.version,allowEmptyWidgets:data.widgets.length===0&&emptied})})}finally{if(emptied)delete root.__vyraUserEmptiedWidgets}overlay=d.overlay;localStorage.removeItem(QUEUE);lastLocal=localStorage.getItem('vyra-state');saveMeta();setStatus('synced');return{ok:true}}catch(e){if(e.status===409){localStorage.setItem(QUEUE,JSON.stringify({at:Date.now(),state:data}));setStatus('conflict');showConflict();return{ok:false,status:409}}else{localStorage.setItem(QUEUE,JSON.stringify({at:Date.now(),state:data}));setStatus('offline');return{ok:false,status:e&&e.status?e.status:0}}}finally{syncing=false}}
  function schedule(){clearTimeout(timer);timer=setTimeout(push,1800)}
  function choice(remote){return new Promise(resolve=>{const modal=document.createElement('div');modal.className='cs-modal';modal.innerHTML='<section><small>FÖRSTA CLOUD-SYNK</small><h2>Vilken layout vill du behålla?</h2><p>Det finns både en layout på den här datorn och en online. Ingenting skrivs över innan du väljer.</p><div><button data-choice="remote">Använd online-versionen</button><button class="primary" data-choice="local">Behåll den här datorns version</button></div></section>';document.body.append(modal);modal.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{modal.remove();resolve(b.dataset.choice)})})}
  function showConflict(){if(document.querySelector('.cs-conflict'))return;const bar=document.createElement('div');bar.className='cs-conflict';bar.innerHTML='<span><b>Synkkonflikt</b><small>Layouten ändrades på en annan dator. Välj vilken version som ska behållas.</small></span><button data-cs-online>Online</button><button class="primary" data-cs-local>Den här datorn</button>';document.body.append(bar);bar.querySelector('[data-cs-online]').onclick=async()=>{try{overlay=await getRemote(overlay.id);apply(overlay.state);saveMeta();localStorage.removeItem(QUEUE);setStatus('synced');bar.remove()}catch{setStatus('offline')}};bar.querySelector('[data-cs-local]').onclick=async()=>{try{overlay=await getRemote(overlay.id);await push();bar.remove()}catch{setStatus('offline')}}}
  async function initialize(detail){if(initialized||!detail?.workspaces?.length)return;initialized=true;workspace=detail.workspaces[0];mountStatus();setStatus('saving','Ansluter cloud…');try{const result=await list(),meta=read(META),items=result.overlays||[];if(!items.length){await create();setStatus('synced');return}const preferred=items.find(x=>x.id===meta?.overlayId)||items[0];overlay=await getRemote(preferred.id);const local=payload(),first=!meta||meta.workspaceId!==workspace.id||meta.overlayId!==overlay.id;if(first&&local?.widgets?.length){const selected=await choice(overlay);if(selected==='remote'){apply(overlay.state);lastLocal=localStorage.getItem('vyra-state');saveMeta();setStatus('synced')}else{await push()}}else{if(meta&&Number(meta.version)<Number(overlay.version)&&localStorage.getItem('vyra-state')!==meta.lastLocal){setStatus('conflict');showConflict()}else if(meta&&Number(meta.version)<Number(overlay.version)){apply(overlay.state);saveMeta();setStatus('synced')}else{saveMeta();setStatus('synced');if(read(QUEUE))schedule()}}}catch{setStatus('offline')}}
  addEventListener('vyra-auth-ready',e=>initialize(e.detail));addEventListener('online',()=>{if(workspace)schedule()});addEventListener('offline',()=>setStatus('offline'));
  setInterval(()=>{mountStatus();if(!workspace)return;const current=localStorage.getItem('vyra-state');if(current&&current!==lastLocal){lastLocal=current;localStorage.setItem(QUEUE,JSON.stringify({at:Date.now(),state:payload()}));schedule()}},1000);
  setTimeout(()=>initialize(root.VyraAuth?.lastDetail?.()),500);
  root.VyraCloudSync={initialize,push,status:()=>status,current:()=>({workspace,overlay})};
})(typeof window!=='undefined'?window:globalThis);
