// Egen text/bild/video som streamern själv fyller i eller laddar upp.
function cwDb(){return new Promise((ok,no)=>{let r=indexedDB.open('vyra-action-media',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('files'))r.result.createObjectStore('files')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function cwStore(file){if(!file)return null;let db=await cwDb(),id='media-'+Date.now()+'-'+Math.random().toString(36).slice(2);await new Promise((ok,no)=>{let tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=ok;tx.onerror=()=>no(tx.error)});db.close();return{id,name:file.name,type:file.type,size:file.size}}
async function cwRead(meta){if(!meta?.id)return null;let db=await cwDb(),value=await new Promise((ok,no)=>{let tx=db.transaction('files'),r=tx.objectStore('files').get(meta.id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});db.close();return value}
const cwUrlCache={};
function cwResolveUrl(meta){if(!meta?.id)return null;if(cwUrlCache[meta.id])return cwUrlCache[meta.id];if(cwUrlCache[meta.id]==='')return null;cwUrlCache[meta.id]='';cwRead(meta).then(blob=>{if(blob){cwUrlCache[meta.id]=URL.createObjectURL(blob);render()}});return null}

function customTextHtml(w){let endless=w.textScrollEndless!==false,speed=w.textScrollSpeed||8,rainbow=w.textRainbow,color=rainbow?'transparent':(w.textColor||'#ffffff'),shadow=rainbow?'none':`${w.textShadowX||0}px ${w.textShadowY||0}px ${w.textShadowBlur||0}px ${w.textShadowColor||'#000000'}`,text=(w.customText||'Skriv din text här').replace(/</g,'&lt;'),span=`<span class="ctw-text${rainbow?' rainbow':''}" style="font-family:${w.textFontFamily||'Inter'};font-size:${w.textFontSize||32}px;color:${color};text-shadow:${shadow}">${text}</span>`;return `<div class="widget custom-text-widget${selected===w.id?' selected':''}" data-id="${w.id}" style="left:${w.x}px;top:${w.y}px;width:${w.width||420}px;height:${w.height||90}px"><div class="ctw-track${endless?' endless':''}" style="--speed:${speed}s">${span}${endless?span:''}</div>${selected===w.id?'<span class="resize-handle">↘</span>':''}</div>`}

function customImageHtml(w){let url=cwResolveUrl(w.mediaMeta),fit=w.mediaFit||'cover';return `<div class="widget custom-image-widget${selected===w.id?' selected':''}" data-id="${w.id}" style="left:${w.x}px;top:${w.y}px;width:${w.width||300}px;height:${w.height||300}px">${url?`<img src="${url}" style="width:100%;height:100%;object-fit:${fit};opacity:${(w.mediaOpacity??100)/100}">`:'<div class="cw-placeholder">Välj en bild i panelen →</div>'}${selected===w.id?'<span class="resize-handle">↘</span>':''}</div>`}

function customVideoHtml(w){let url=cwResolveUrl(w.mediaMeta),fit=w.mediaFit||'cover';return `<div class="widget custom-video-widget${selected===w.id?' selected':''}" data-id="${w.id}" style="left:${w.x}px;top:${w.y}px;width:${w.width||300}px;height:${w.height||450}px">${url?`<video src="${url}" autoplay loop muted playsinline style="width:100%;height:100%;object-fit:${fit};opacity:${(w.mediaOpacity??100)/100}"></video>`:'<div class="cw-placeholder">Välj en video i panelen →</div>'}${selected===w.id?'<span class="resize-handle">↘</span>':''}</div>`}

function customTextProps(w){let general=`<label>Text<textarea id="ctwText" rows="3">${w.customText||''}</textarea></label><div class="switch-row one"><label><input id="ctwEndless" type="checkbox" ${w.textScrollEndless!==false?'checked':''}> Rulla oändligt</label></div><label class="range-label">Rullhastighet <b>${w.textScrollSpeed||8}s</b><input id="ctwSpeed" type="range" min="2" max="30" value="${w.textScrollSpeed||8}"></label>`,font=`<label>Typsnitt<select id="ctwFont"><option value="Inter">Inter</option><option value="Arial">Arial</option><option value="Georgia">Georgia</option><option value="Impact">Impact</option><option value="monospace">Mono</option></select></label><label class="range-label">Textstorlek <b>${w.textFontSize||32}px</b><input id="ctwSize" type="range" min="12" max="120" value="${w.textFontSize||32}"></label><div class="color-grid"><label>Textfärg<input id="ctwColor" type="color" value="${w.textColor||'#ffffff'}"></label></div><div class="switch-row one"><label><input id="ctwRainbow" type="checkbox" ${w.textRainbow?'checked':''}> Regnbågsfärg</label></div>`,shadow=`<div class="property-grid"><label>X<input id="ctwShadowX" type="number" value="${w.textShadowX||0}"></label><label>Y<input id="ctwShadowY" type="number" value="${w.textShadowY||0}"></label><label>Blur<input id="ctwShadowBlur" type="number" value="${w.textShadowBlur||0}"></label></div><div class="color-grid"><label>Skuggfärg<input id="ctwShadowColor" type="color" value="${w.textShadowColor||'#000000'}"></label></div>`;return `<h3>EGEN TEXT</h3><div hidden><input id="pt" value="${w.title||''}"><input id="pv" value=""></div>${pgSection('TEXT',general,true)}${pgSection('TYPSNITT',font,false)}${pgSection('SKUGGA',shadow,false)}<div class="property-group"><h4>POSITION & STORLEK</h4><div class="property-grid"><label>X<input id="propX" type="number" value="${w.x||0}"></label><label>Y<input id="propY" type="number" value="${w.y||0}"></label><label>Bredd<input id="propWidth" type="number" value="${w.width||420}"></label><label>Lager<input id="propLayer" type="number" value="${w.layer||1}"></label></div></div><button class="delete" id="del">Ta bort</button>`}

function customMediaProps(w,accept,label){let general=`<label>${label}<input id="cwFile" type="file" accept="${accept}"></label>${w.mediaMeta?`<small class="cw-filename">${w.mediaMeta.name}</small>`:''}<label>Anpassning<select id="cwFit"><option value="cover">Fyll (beskär)</option><option value="contain">Anpassa (visa allt)</option></select></label><label class="range-label">Opacitet <b>${w.mediaOpacity??100}%</b><input id="cwOpacity" type="range" min="0" max="100" value="${w.mediaOpacity??100}"></label>`;return `<h3>${label.toUpperCase()}</h3><div hidden><input id="pt" value="${w.title||''}"><input id="pv" value=""></div><div class="property-group"><h4>INNEHÅLL</h4>${general}</div><div class="property-group"><h4>POSITION & STORLEK</h4><div class="property-grid"><label>X<input id="propX" type="number" value="${w.x||0}"></label><label>Y<input id="propY" type="number" value="${w.y||0}"></label><label>Bredd<input id="propWidth" type="number" value="${w.width||300}"></label><label>Lager<input id="propLayer" type="number" value="${w.layer||1}"></label></div></div><button class="delete" id="del">Ta bort</button>`}

function customTextBind(w){bindCollapsibleGroups(document.querySelector('.properties'));let set=(id,key,num=false)=>{let el=document.querySelector(id);if(el)el.onchange=e=>{w[key]=num?+e.target.value:e.target.value;save();render()}};let text=document.querySelector('#ctwText');if(text)text.oninput=e=>{w.customText=e.target.value;save();render()};let endless=document.querySelector('#ctwEndless');if(endless)endless.onchange=e=>{w.textScrollEndless=e.target.checked;save();render()};set('#ctwSpeed','textScrollSpeed',true);set('#ctwFont','textFontFamily');set('#ctwSize','textFontSize',true);set('#ctwColor','textColor');let rainbow=document.querySelector('#ctwRainbow');if(rainbow)rainbow.onchange=e=>{w.textRainbow=e.target.checked;save();render()};set('#ctwShadowX','textShadowX',true);set('#ctwShadowY','textShadowY',true);set('#ctwShadowBlur','textShadowBlur',true);set('#ctwShadowColor','textShadowColor');let font=document.querySelector('#ctwFont');if(font)font.value=w.textFontFamily||'Inter'}

function customMediaBind(w){let file=document.querySelector('#cwFile');if(file)file.onchange=async e=>{let f=e.target.files[0];if(!f)return;w.mediaMeta=await cwStore(f);delete cwUrlCache[w.mediaMeta.id];save();render();toast('Fil vald: '+f.name)};let fit=document.querySelector('#cwFit');if(fit){fit.value=w.mediaFit||'cover';fit.onchange=e=>{w.mediaFit=e.target.value;save();render()}}let op=document.querySelector('#cwOpacity');if(op)op.oninput=e=>{w.mediaOpacity=+e.target.value;save();render()}}

const CUSTOM_TYPES=['templateCustomText','templateCustomImage','templateCustomVideo'];
const customWidgetsWh=wh;wh=function(w){if(w.type==='templateCustomText')return customTextHtml(w);if(w.type==='templateCustomImage')return customImageHtml(w);if(w.type==='templateCustomVideo')return customVideoHtml(w);return customWidgetsWh(w)};
const customWidgetsProps=props;props=function(){let w=state.widgets.find(x=>x.id===selected);if(!w||!CUSTOM_TYPES.includes(w.type))return customWidgetsProps();if(w.type==='templateCustomText')return customTextProps(w);if(w.type==='templateCustomImage')return customMediaProps(w,'image/*','Bild');return customMediaProps(w,'video/*','Video')};
const customWidgetsBind=bind;bind=function(){customWidgetsBind();if(view!=='editor')return;let w=state.widgets.find(x=>x.id===selected);if(!w||!CUSTOM_TYPES.includes(w.type))return;if(w.type==='templateCustomText')customTextBind(w);else customMediaBind(w)};
const customResizeBind=bind;bind=function(){customResizeBind();if(view!=='editor')return;let w=state.widgets.find(x=>x.id===selected);if(!w||!CUSTOM_TYPES.includes(w.type))return;let handle=document.querySelector('.resize-handle');if(!handle)return;handle.onpointerdown=e=>{e.preventDefault();e.stopPropagation();let widget=handle.closest('.widget'),startX=e.clientX,startY=e.clientY,startWidth=w.width||300,startHeight=w.height||300;handle.setPointerCapture(e.pointerId);handle.onpointermove=ev=>{w.width=Math.max(60,Math.round(startWidth+(ev.clientX-startX)));w.height=Math.max(40,Math.round(startHeight+(ev.clientY-startY)));widget.style.width=w.width+'px';widget.style.height=w.height+'px'};handle.onpointerup=()=>{handle.onpointermove=null;save();render()}}};
const customWidgetsCatalog=bind;bind=function(){customWidgetsCatalog();if(view!=='editor'&&view!=='overlay')return;let catalog=document.querySelector('.widget-catalog');if(!catalog||catalog.querySelector('[data-custom-widgets]'))return;let section=document.createElement('section');section.dataset.customWidgets='1';section.className='glove-snipe-template-section';section.innerHTML='<h4>EGET INNEHÅLL</h4><div><button data-cw="text"><i>T</i><span><b>Text</b><small>Egen rullande text</small></span></button><button data-cw="image"><i>▤</i><span><b>Bild</b><small>Egen bildfil</small></span></button><button data-cw="video"><i>▶</i><span><b>Video</b><small>Egen videofil</small></span></button></div>';catalog.prepend(section);section.querySelectorAll('button').forEach(b=>b.onclick=()=>{let kind=b.dataset.cw,type=kind==='text'?'templateCustomText':kind==='image'?'templateCustomImage':'templateCustomVideo',id=type+Date.now(),defaults=kind==='text'?{x:60,y:120,width:420,height:90,customText:'Skriv din text här'}:{x:60,y:120,width:300,height:kind==='video'?450:300};state.widgets.push({id,type,...defaults});selected=id;save();render();toast((kind==='text'?'Text':kind==='image'?'Bild':'Video')+'-widget skapad')})};
