(function(root){
  'use strict';
  const API='/api',POLL_MS=650,STATUS_MS=5000,MAX_QUEUE=2000,BATCH_SIZE=40,listeners=new Set(),seenKeys=new Map(),queue=[];
  let last=Number(sessionStorage.getItem('vyra-last-live-event')||0),online=false,processing=false,dropped=0,processed=0,pollErrors=0,lastLatency=0,lastPollAt=0,cloudSource=null,cloudReconnects=0;
  async function json(url,options){const started=performance.now(),r=await fetch(API+url,{cache:'no-store',headers:{'Content-Type':'application/json'},...options});lastLatency=Math.round(performance.now()-started);if(!r.ok)throw Error('Serverfel '+r.status);return r.json()}
  function emit(name,detail){dispatchEvent(new CustomEvent(name,{detail}));listeners.forEach(fn=>{try{fn(detail)}catch{}})}
  async function status(){try{const d=await json('/status');if(Number(d.lastEventId||0)<last){last=0;sessionStorage.setItem('vyra-last-live-event','0');seenKeys.clear()}online=true;emit('vyra-server-status',{...d,client:metrics()});return d}catch(e){if(online){online=false;emit('vyra-server-offline',{error:e.message,client:metrics()})}throw e}}
  function mappedEvent(e){const t=String(e.type||'').toLowerCase(),payload={username:e.username,name:e.name||e.username,gift:e.giftName,giftname:e.giftName,profileImage:e.profileImage,coins:e.coins,count:e.count,repeatcount:e.count,combo:e.count,value:e.name||e.giftName||e.username};if(t==='gift')return[e.count>1?'giftCombo':'gift',payload];if(t==='follow')return['follow',payload];if(t==='member'||t==='subscribe')return['member',payload];if(t==='share')return['share',payload];if(t==='likes'||t==='like')return['likes',{...payload,value:e.count}];if(t==='chatcommand')return['chatCommand',{...payload,command:e.name,value:e.name}];if(t==='chat')return['chat',{...payload,comment:e.name,value:e.name}];return null}
  function dispatchLive(e){const normalized=root.VyraTikTokEvents?.normalize(e)||e;localStorage.setItem('vyra-live-event',JSON.stringify(normalized));emit('vyra-live-event',normalized);root.VyraTikTokEvents?.route(normalized);root.routeLiveBattleEvent?.(normalized);const mapped=mappedEvent(normalized);if(mapped&&root.VyraActionEvent){root.VyraActionEvent.handleEvent(mapped[0],mapped[1]);if(mapped[0]==='member')root.VyraActionEvent.handleEvent('join',mapped[1])}processed++}
  function processQueue(){if(processing)return;processing=true;const run=()=>{const started=performance.now();let count=0;while(queue.length&&count<BATCH_SIZE&&performance.now()-started<10){dispatchLive(queue.shift());count++}if(queue.length)setTimeout(run,16);else processing=false};run()}
  function enqueue(e){if(queue.length>=MAX_QUEUE){let index=queue.findIndex(x=>/likes?/i.test(x.type||''));if(index<0)index=0;queue.splice(index,1);dropped++}queue.push(e);processQueue()}
  function accept(e,now){last=Math.max(last,Number(e.id||0));sessionStorage.setItem('vyra-last-live-event',String(last));const key=e.eventKey||('id:'+e.id);if(seenKeys.has(key))return false;seenKeys.set(key,now);enqueue(e);return true}
  function acceptCloud(e){const mapped={...e,eventKey:e.id,profileImage:e.profileUrl,coins:e.value,points:e.value,name:e.username};if(seenKeys.has(mapped.eventKey))return;seenKeys.set(mapped.eventKey,Date.now());enqueue(mapped)}
  function connectCloud(detail){const workspaceId=detail?.workspaces?.[0]?.id;if(!workspaceId||cloudSource)return;cloudSource=new EventSource(`/api/workspaces/${workspaceId}/events/stream`);cloudSource.addEventListener('live',message=>{try{acceptCloud(JSON.parse(message.data));emit('vyra-cloud-live',{connected:true,workspaceId})}catch{}});cloudSource.onopen=()=>emit('vyra-cloud-live',{connected:true,workspaceId,reconnects:cloudReconnects});cloudSource.onerror=()=>{cloudReconnects++;emit('vyra-cloud-live',{connected:false,workspaceId,reconnects:cloudReconnects})}}
  async function poll(){try{const d=await json('/events?after='+last),now=Date.now();lastPollAt=now;for(const[k,at]of seenKeys)if(now-at>120000)seenKeys.delete(k);for(const e of d.events||[])accept(e,now)}catch{pollErrors++}finally{setTimeout(poll,POLL_MS)}}
  function metrics(){return{online,lastEventId:last,queueDepth:queue.length,maxQueue:MAX_QUEUE,processed,dropped,pollErrors,pollLatency:lastLatency,lastPollAt}}
  root.VyraLive={status,connect:username=>json('/connect',{method:'POST',body:JSON.stringify({username})}),disconnect:()=>json('/disconnect',{method:'POST',body:'{}'}),send:event=>json('/events',{method:'POST',body:JSON.stringify(event)}),ingest:acceptCloud,on(fn){listeners.add(fn);return()=>listeners.delete(fn)},metrics};
  addEventListener('vyra-auth-ready',e=>connectCloud(e.detail));
  status().catch(()=>{});setInterval(()=>status().catch(()=>{}),STATUS_MS);poll();
})(typeof window!=='undefined'?window:globalThis);
