(function(root){
  'use strict';
  const MAX_EVENTS=200, events=[];
  const stats={online:false,connected:false,connectionState:'idle',username:'',received:0,errors:0,reconnects:0,lastEventAt:0,lastPollAt:0,pollLatency:0,queueDepth:0,maxQueue:2000,dropped:0,processed:0};
  const battle={active:false,scoreUs:0,scoreThem:0,lastKind:'—',lastAt:0,multiplier:1,mvp:'—',events:0};
  let opened=false, filter='all', query='';

  function safe(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function actionMatches(event){
    try{
      const state=JSON.parse(localStorage.getItem('vyra-action-event-v2')||'{"actions":[],"events":[]}');
      const mapped=mapTrigger(event), value=String(mapped.payload.value??mapped.payload.gift??mapped.payload.command??'').toLowerCase();
      return state.events.filter(e=>e.enabled&&(e.advancedTrigger||e.trigger)===mapped.trigger&&(!String(e.triggerValue||e.condition||'')||value.includes(String(e.triggerValue||e.condition).toLowerCase()))).map(e=>state.actions.find(a=>a.id===(e.actionId||(e.allActionIds||[])[0]))?.name||'Automation');
    }catch{return []}
  }
  function widgetMatches(event){
    const type=String(event.type||'').toLowerCase(), all=Array.isArray(root.state?.widgets)?root.state.widgets:[];
    return all.filter(w=>{const kind=String(w.type||w.group||'').toLowerCase();return !w.hidden&&((type.includes('gift')&&(String(w.group||'').includes('Gift')||kind.includes('gift')))||(type.includes('like')&&kind.includes('like'))||(type.includes('follow')&&kind.includes('follow'))||(type.includes('battle')&&(kind.includes('battle')||kind.includes('glovesnipe'))))}).map(w=>w.title||w.type).slice(0,5);
  }
  function mapTrigger(e){const t=String(e.type||'').toLowerCase(),p={username:e.username,name:e.name||e.username,gift:e.giftName,giftname:e.giftName,profileImage:e.profileImage,coins:e.coins,count:e.count,repeatcount:e.count,combo:e.count,value:e.name||e.giftName||e.username};if(t==='gift')return{trigger:e.count>1?'giftCombo':'gift',payload:p};if(t==='follow')return{trigger:'follow',payload:p};if(t==='member'||t==='subscribe')return{trigger:'member',payload:p};if(t==='share')return{trigger:'share',payload:p};if(t==='likes'||t==='like')return{trigger:'likes',payload:{...p,value:e.count}};if(t==='chatcommand')return{trigger:'chatCommand',payload:{...p,command:e.name,value:e.name}};return{trigger:t,payload:p}}
  function record(raw){
    const event={...raw,_receivedAt:Date.now(),_actions:actionMatches(raw),_widgets:widgetMatches(raw)};
    event._status=event._actions.length||event._widgets.length?'triggad':'ej matchad';
    events.unshift(event);if(events.length>MAX_EVENTS)events.length=MAX_EVENTS;
    stats.received++;stats.lastEventAt=event._receivedAt;
    updateBattle(raw);
    if(opened)render();
  }
  function battleKind(event){const type=String(event.type||event.event||'').toLowerCase(),mult=+(event.multiplier||event.x||event.combo||0);if(type.includes('battle_start'))return'start';if(type.includes('battle_end'))return'end';if(type.includes('battle_mvp')||type==='mvp')return'mvp';if(type.includes('snipe'))return'snipe';if(type.includes('glove'))return'glove';if(type.includes('tap'))return'tap';if(type.includes('x3')||mult===3)return'x3';if(type.includes('x2')||mult===2)return'x2';if(type.includes('battle')||event.scoreUs!=null||event.scoreThem!=null)return'score';return''}
  function updateBattle(event){const kind=battleKind(event);if(!kind)return;battle.events++;battle.lastKind=kind.toUpperCase();battle.lastAt=Date.now();if(kind==='start')battle.active=true;if(kind==='end')battle.active=false;if(kind==='x2')battle.multiplier=2;if(kind==='x3')battle.multiplier=3;if(kind==='mvp')battle.mvp=event.username||event.name||'Okänd';if(event.scoreUs!=null)battle.scoreUs=+event.scoreUs||0;if(event.scoreThem!=null)battle.scoreThem=+event.scoreThem||0;if(event.ourScore!=null)battle.scoreUs=+event.ourScore||0;if(event.opponentScore!=null)battle.scoreThem=+event.opponentScore||0}
  function configuredBattle(){const all=Array.isArray(root.state?.widgets)?root.state.widgets:[],kinds=['boost','tap','glove','snipe'];return Object.fromEntries(kinds.map(k=>[k,all.filter(w=>w.type==='templateGloveSnipe'&&!w.hidden&&String(w.battleEventKind||'boost')===k).length]))}
  function testBattle(kind){const map={x2:{type:'battle_x2',multiplier:2},x3:{type:'battle_x3',multiplier:3},tap:{type:'battle_tap',multiplier:2},glove:{type:'battle_glove',multiplier:2},snipe:{type:'battle_snipe',multiplier:2},mvp:{type:'battle_mvp',name:'Test MVP',username:'Test MVP',score:15000},start:{type:'battle_start'},end:{type:'battle_end'}};const event={id:Date.now(),timestamp:Date.now(),__test:true,...map[kind]};root.routeLiveBattleEvent?.(event);record(event);root.toast?.('Battle-test: '+kind.toUpperCase())}
  function replay(id){const e=events.find(x=>String(x.id)===String(id));if(!e)return;const copy={...e,id:Date.now(),timestamp:Date.now(),__replay:true};delete copy._actions;delete copy._widgets;delete copy._status;delete copy._receivedAt;root.routeLiveBattleEvent?.(copy);const m=mapTrigger(copy);root.VyraActionEvent?.handleEvent?.(m.trigger,{...m.payload,__test:true});root.toast?.('Eventet kördes igen lokalt')}
  function rate(){const cutoff=Date.now()-60000;return events.filter(e=>e._receivedAt>=cutoff).length}
  function filtered(){return events.filter(e=>(filter==='all'||String(e.type).toLowerCase()===filter)&&(!query||JSON.stringify(e).toLowerCase().includes(query))).slice(0,80)}
  function row(e){const hits=[...e._actions.map(x=>'⚡ '+x),...e._widgets.map(x=>'◇ '+x)];return `<tr><td><time>${new Date(e._receivedAt).toLocaleTimeString('sv-SE')}</time><b>${safe(e.type||'okänd')}</b></td><td><b>${safe(e.username||e.name||'—')}</b><small>${safe(e.giftName||e.name||'')}</small></td><td><span class="lc-status ${e._status==='triggad'?'ok':'idle'}">${e._status}</span><small>${hits.length?safe(hits.join(' · ')):'Ingen aktiv regel/widget matchade'}</small></td><td><button data-replay="${safe(e.id)}">Kör igen</button></td></tr>`}
  function mountPerformance(){const health=document.querySelector('.lc-health');if(!health)return;const load=Math.min(100,Math.round((stats.queueDepth/Math.max(1,stats.maxQueue))*100)),section=document.createElement('section');section.className='lc-performance';section.innerHTML=`<header><span><small>PRESTANDA & KRASCHSKYDD</small><b>${load<50?'Stabil':load<80?'Hög belastning':'Kritisk kö'}</b></span><em>${load}% köbelastning</em></header><div class="lc-load"><i style="width:${load}%"></i></div><div><span>Kö <b>${stats.queueDepth}/${stats.maxQueue}</b></span><span>Bearbetade <b>${stats.processed}</b></span><span>Fördröjning <b>${stats.pollLatency} ms</b></span><span>Skyddade/droppade <b>${stats.dropped}</b></span></div>`;health.after(section)}
  function mountBattle(){const panel=document.querySelector('.lc-panel');if(!panel)return;const configured=configuredBattle(),ready=configured.boost+configured.tap+configured.glove+configured.snipe,section=document.createElement('section');section.className='lc-battle';section.innerHTML=`<header><div><small>LIVE MATCH</small><h3>Match Monitor</h3></div><span class="lc-match-state ${battle.active?'active':''}">${battle.active?'MATCH AKTIV':'VÄNTAR'}</span></header><div class="lc-score"><div><small>DITT LAG</small><strong>${battle.scoreUs.toLocaleString('sv-SE')}</strong></div><b>×${battle.multiplier}</b><div><small>MOTSTÅNDARE</small><strong>${battle.scoreThem.toLocaleString('sv-SE')}</strong></div></div><div class="lc-battle-meta"><span>Senaste: <b>${safe(battle.lastKind)}</b></span><span>MVP: <b>${safe(battle.mvp)}</b></span><span>Battle-event: <b>${battle.events}</b></span><span>Aktiva effekter: <b>${ready}</b></span></div><div class="lc-battle-ready"><span class="${configured.boost?'ok':''}">X2/X3 ${configured.boost||'saknas'}</span><span class="${configured.tap?'ok':''}">Tap ${configured.tap||'saknas'}</span><span class="${configured.glove?'ok':''}">Glove ${configured.glove||'saknas'}</span><span class="${configured.snipe?'ok':''}">Snipe ${configured.snipe||'saknas'}</span></div><div class="lc-battle-tests"><button data-battle-test="start">Start</button><button data-battle-test="x2">X2</button><button data-battle-test="x3">X3</button><button data-battle-test="tap">Tap</button><button data-battle-test="glove">Glove</button><button data-battle-test="snipe">Snipe</button><button data-battle-test="mvp">MVP</button><button data-battle-test="end">Avsluta</button></div>`;panel.before(section);section.querySelectorAll('[data-battle-test]').forEach(b=>b.onclick=()=>testBattle(b.dataset.battleTest))}
  function render(){
    opened=true;document.querySelectorAll('aside button').forEach(b=>b.classList.toggle('active',b.dataset.extra==='liveControl'));
    // #crumb skrivs INTE har langre. Den harleds ur navetiketten av capture-lyssnaren i
    // studio.js (vyraSyncCrumb); den har filen var den gamla enda skrivaren, och en sen
    // setTimeout-render harifran skrev over den harledda brodsmulan med fel ord.
    const title=document.querySelector('#title'),view=document.querySelector('#view');if(!view)return;
    // Rubriken maste vara SAMMA ORD som navetiketten — husets navkontrakt (nav-state.browser).
    // Vyns egna H2 far garna heta "LIVE Control Center"; #title far inte.
    if(title)title.textContent='LIVE-kontroll';
    const types=[...new Set(events.map(e=>String(e.type||'okänd').toLowerCase()))];
    const tikStatus=stats.connected?safe(stats.username||'Ansluten'):stats.connectionState==='reconnecting'?'Återansluter':stats.connectionState==='stale'?'Signal saknas':'Väntar på connector';
    view.innerHTML=`<div class="lc-page"><div class="lc-head"><div><h2>LIVE Control Center</h2><p>Se varje TikTok-event, vad som matchade och varför inget hände.</p></div><button id="lcTest" class="primary">Skicka testgåva</button></div><div class="lc-health"><article><i class="${stats.online?'ok':''}"></i><span><small>SERVER</small><b>${stats.online?'Online':'Offline'}</b></span></article><article><i class="${stats.connected?'ok':'warn'}"></i><span><small>TIKTOK</small><b>${tikStatus}</b></span></article><article><span><small>EVENT / MIN</small><b>${rate()}</b></span></article><article><span><small>MOTTAGNA</small><b>${stats.received}</b></span></article><article><span><small>FEL</small><b>${stats.errors}</b></span></article></div><section class="lc-panel"><header><div><h3>Event Inspector</h3><span>${events.length} event i lokal historik</span></div><div><input id="lcSearch" value="${safe(query)}" placeholder="Sök namn, gift eller event"><select id="lcFilter"><option value="all">Alla event</option>${types.map(t=>`<option value="${safe(t)}" ${filter===t?'selected':''}>${safe(t)}</option>`).join('')}</select><button id="lcClear">Rensa</button></div></header><div class="lc-table"><table><thead><tr><th>Tid / event</th><th>Person / data</th><th>Resultat</th><th>Test</th></tr></thead><tbody>${filtered().length?filtered().map(row).join(''):'<tr><td colspan="4" class="lc-empty">Inga event ännu. Starta LIVE-connectorn eller skicka ett testevent.</td></tr>'}</tbody></table></div></section></div>`;
    mountPerformance();mountBattle();document.querySelector('#lcSearch').oninput=e=>{query=e.target.value.toLowerCase();render()};document.querySelector('#lcFilter').onchange=e=>{filter=e.target.value;render()};document.querySelector('#lcClear').onclick=()=>{events.length=0;render()};document.querySelector('#lcTest').onclick=()=>root.VyraLive?.send({type:'gift',username:'TestViewer',name:'TestViewer',giftName:'Rose',coins:1,count:1});document.querySelectorAll('[data-replay]').forEach(b=>b.onclick=()=>replay(b.dataset.replay));
  }
  addEventListener('vyra-server-status',e=>{const wasConnected=stats.connected,c=e.detail?.connection||{},client=e.detail?.client||root.VyraLive?.metrics?.()||{};stats.online=true;stats.connected=!!c.connected;stats.connectionState=c.state||'idle';stats.username=c.username||'';stats.reconnects=Math.max(stats.reconnects,Number(c.reconnectAttempt||0));stats.queueDepth=Number(client.queueDepth||0);stats.maxQueue=Number(client.maxQueue||2000);stats.dropped=Number(client.dropped||0);stats.processed=Number(client.processed||0);stats.pollLatency=Number(client.pollLatency||0);if(!wasConnected&&stats.connected&&stats.received)stats.reconnects++;if(opened)render()});
  addEventListener('vyra-server-offline',()=>{stats.online=false;stats.connected=false;stats.errors++;if(opened)render()});
  addEventListener('vyra-live-event',e=>record(e.detail||{}));
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-extra="liveControl"]');if(b){e.preventDefault();setTimeout(render)}});
  root.VyraLiveControl={render,record,replay,testBattle,getSnapshot:()=>({stats:{...stats,eventRate:rate()},battle:{...battle},events:events.map(e=>({...e}))})};
})(typeof window!=='undefined'?window:globalThis);
