(function(root){
  'use strict';
  const params=new URLSearchParams(location.search),access=params.get('access');
  function api(path,options){return root.VyraAuth.api(path,options)}
  function apply(remote){if(!remote||!Array.isArray(remote.widgets))throw Error('Ogiltig overlay');const copy={...remote},meta=copy.__vyraCloud;delete copy.__vyraCloud;localStorage.setItem('vyra-state',JSON.stringify(copy));Object.entries(meta?.storage||{}).forEach(([key,value])=>{if(typeof value==='string')localStorage.setItem(key,value)});if(typeof state==='object'){Object.keys(state).forEach(key=>delete state[key]);Object.assign(state,copy)}root.render?.()}
  async function startViewer(){try{const response=await fetch(`/api/overlay-access/${encodeURIComponent(access)}`,{cache:'no-store',referrerPolicy:'no-referrer'});if(!response.ok)throw Error('OBS-länken är spärrad eller har gått ut');const data=await response.json();apply(data.overlay.state);const source=new EventSource(`/api/overlay-access/${encodeURIComponent(access)}/events/stream`);source.addEventListener('live',message=>{try{const event=JSON.parse(message.data);if(root.VyraLive?.ingest)root.VyraLive.ingest(event);else setTimeout(()=>root.VyraLive?.ingest?.(event),250)}catch{}});source.onopen=()=>document.documentElement.dataset.overlayConnection='connected';source.onerror=()=>document.documentElement.dataset.overlayConnection='reconnecting'}catch(error){document.body.innerHTML=`<div style="font:600 16px system-ui;color:#fff;background:#170b20;padding:18px;border:1px solid #8d3cff;border-radius:12px">${error.message}</div>`}}
  function modal(){let el=document.querySelector('.oa-modal');if(el)return el;el=document.createElement('div');el.className='oa-modal';el.innerHTML='<section><button class="oa-close">×</button><small>SÄKRA OBS-LÄNKAR</small><h2>Overlay-åtkomst</h2><p>Varje länk kan spärras direkt utan att ändra ditt lösenord.</p><div class="oa-create"><input class="oa-label" value="OBS huvuddator" maxlength="80"><select class="oa-days"><option value="30">30 dagar</option><option value="90">90 dagar</option><option value="365">1 år</option><option value="">Utan slutdatum</option></select><button class="primary oa-new">Skapa länk</button></div><div class="oa-result"></div><div class="oa-list"></div></section>';document.body.append(el);el.querySelector('.oa-close').onclick=()=>el.remove();return el}
  async function openManager(){const current=root.VyraCloudSync?.current?.(),workspace=current?.workspace,overlay=current?.overlay;if(!workspace||!overlay)return root.toast?.('Vänta tills cloud-synken är ansluten');const el=modal(),base=`/api/workspaces/${workspace.id}/overlays/${overlay.id}/access-tokens`;async function refresh(){try{const data=await api(base);el.querySelector('.oa-list').innerHTML=(data.tokens||[]).map(token=>`<article class="${token.revoked_at?'revoked':''}"><span><b>${token.label}</b><small>${token.revoked_at?'Spärrad':token.expires_at?'Gäller till '+new Date(token.expires_at).toLocaleDateString('sv-SE'):'Utan slutdatum'}</small></span>${token.revoked_at?'':'<button data-revoke="'+token.id+'">Spärra</button>'}</article>`).join('')||'<p>Inga OBS-länkar ännu.</p>';el.querySelectorAll('[data-revoke]').forEach(button=>button.onclick=async()=>{await api(base+'/'+button.dataset.revoke,{method:'DELETE'});refresh()})}catch(error){el.querySelector('.oa-list').textContent=error.message}}el.querySelector('.oa-new').onclick=async()=>{try{const days=el.querySelector('.oa-days').value,data=await api(base,{method:'POST',body:JSON.stringify({label:el.querySelector('.oa-label').value,expiresInDays:days?Number(days):null})});el.querySelector('.oa-result').innerHTML='<input readonly><button>Kopiera</button><small>Visas bara nu. Spara den direkt i OBS.</small>';const input=el.querySelector('.oa-result input');input.value=data.overlayUrl;el.querySelector('.oa-result button').onclick=async()=>{await navigator.clipboard.writeText(data.overlayUrl);root.toast?.('OBS-länken kopierad')};refresh()}catch(error){el.querySelector('.oa-result').textContent=error.message}};refresh()}
  function mount(){if(access)return startViewer();const actions=document.querySelector('.head-actions');if(!actions||actions.querySelector('.oa-open'))return;const button=document.createElement('button');button.className='oa-open';button.textContent='Säker OBS-länk';button.onclick=openManager;actions.append(button)}
  if(document.readyState==='loading')addEventListener('DOMContentLoaded',mount);else mount();setTimeout(mount,1200);
})(typeof window!=='undefined'?window:globalThis);
