(function(){
  const STREAKS={
    liquid:['Liquid Gold Fuse','#d9a441'],momentum:['Momentum Steps','#d8dee9'],tier:['Momentum Tier','#c68cff'],thread:['Silk Golden Thread','#e7bc63'],chrono:['Chronograph Timeline','#9db7d0'],chain:['Jewelry Chain Reaction','#d2d5da'],thermo:['Thermochromic Gauge','#ff8a36']
  };
  // Menyn i media.js maste kanna till de har designerna. Utan en last lista maste namnen
  // dubbleras dar, och dubblerade listor ar precis det som gled isar: Stil-menyn listade bara
  // de klassiska sju och pastod darfor fel design for alla premium.
  window.VyraStreakPremium=STREAKS;
  const TOP_GIFTS={
    royal:'Royal Gold',neon:'Neon Purple',cyber:'Cyber Blue',glass:'Glass',sakura:'Sakura Pink',fire:'Inferno Fire',ice:'Ice Crystal',galaxy:'Galaxy',aurora:'Aurora',retro:'Retro',goldrush:'Gold Rush',
    hall:'VYRA Hall of Fame',throne:'Royal Throne',champion:'Celestial Champion',pedestal:'Diamond Pedestal',arch:'Celestial Arch',phoenix:'Phoenix Ribbon',signal:'Neon Signal',fireworks:'Celestial Fireworks',bloom:'Crystal Bloom',comet:'Royal Comet'
  };
  const GOALS={crystal:'Crystal Path',celestial:'Celestial Journey',royal:'Royal Community',pulse:'Neon Pulse',garden:'Garden Growth',portal:'Portal Progress',constellation:'Community Constellation','rose-frame':'Rose Crystal Frame','heart-frame':'Royal Heart Frame','sapphire-frame':'Sapphire Dragon Frame','azure-frame':'Azure Crown Frame'};
  const fallbackProfile='assets/images/test/test-profile.png',fallbackGift='assets/gifts/events/0001_Rose.png';
  // Named safeImg but neither escaped nor validated anything: it interpolated the URL straight into
  // src="…" and again into an inline onerror handler, so an avatar URL carrying a quote closed both
  // attributes. Premium widgets are not loaded today, which is exactly why this had to be fixed
  // before they ship rather than after. Both slots now go through VyraSafe.url — the fallback too,
  // because it ends up inside a single-quoted JS string in the handler.
  const safeImg=(src,fallback)=>`src="${VyraSafe.url(src,fallback)}" onerror="this.onerror=null;this.src='${VyraSafe.url(fallback)}'"`;

  // Ramdesignerna ritas av media.js:s vyraStreak, som bar .sframe-art och den urstansade
  // profilrutan. Den har overskrivningen tog ALLA Top Streak-widgets, aven de atta som bar
  // streakFrame, och gjorde ramgrenen till dod kod. Uppmatt i webblasaren:
  //
  //     catalog:topstreak:frame:rose-heart
  //       widgetobjekt:  streakFrame: "rose-heart"        ratt
  //       renderad:      premium-streak streak-liquid     fel
  //
  // Widgetobjektet var alltsa korrekt hela tiden; renderaren laste det bara aldrig. Darfor kunde
  // ingen faltjamforelse fanga det — se tests/renderer-honors-widget.test.js.
  //
  // Brast 2026-08-04 i PR #51, nar media.js borjade injicera den har filen. Ramarna lades till
  // 2026-08-01 och fungerade i tre dagar.
  const klassiskStreak=vyraStreak;
  vyraStreak=function(w){if(w.streakFrame)return klassiskStreak(w);let style=w.streakTheme||'liquid',value=w.dataValue||18;return `<div class="widget vyra-streak premium-streak streak-${style}${selected===w.id?' selected':''}" data-id="${w.id}" style="left:${w.x}px;top:${w.y}px;width:${w.width||520}px;--streak:${w.accent||STREAKS[style]?.[1]||'#d9a441'};--speed:${w.streakSpeed||1};--gift-size:${w.giftSize||64}px;--streak-glow:${w.streakGlow??50}%;zoom:${w.widgetScale||1}"><div class="streak-identity"><div class="streak-flip"><div class="streak-profile-face"><img ${safeImg(w.profileImage,fallbackProfile)}></div><div class="streak-gift-face"><img ${safeImg(w.giftImage,fallbackGift)}></div></div><div class="streak-copy"><small>${w.templateTitle||'TOP STREAK'}</small><strong>${VyraSafe.text(w.dataName,'@StreamQueen')}</strong></div></div><div class="streak-score"><b>${w.streakPrefix??'×'}${value}</b><span>${w.streakLabel||'STREAK'}</span></div><div class="streak-mechanism"><i></i><i></i><i></i><i></i><i></i><em>GOOD</em><em>GREAT</em><em>AMAZING</em><em>LEGENDARY</em></div>${selected===w.id?'<span class="resize-handle">↘</span>':''}</div>`};

  const klassiskTopGift=vyraTopGift;
  vyraTopGift=function(w){if(w.giftFrame)return klassiskTopGift(w);let style=w.theme||'royal';return `<div class="widget vyra-topgift premium-topgift topgift-${style}${selected===w.id?' selected':''}" data-id="${w.id}" style="left:${w.x}px;top:${w.y}px;width:${w.width||340}px;--accent:${w.accent||'#d9a441'};--gift-size:${w.giftSize||110}px;--topgift-glow:${w.topGiftGlow??55}%;--flip-speed:${w.topGiftFlipSpeed||1};zoom:${w.widgetScale||1}"><div class="topgift-ornament"><i></i><i></i><i></i></div><div class="vyra-gift-title">${w.templateTitle||'TOP GIFTER'}</div><div class="vyra-flip"><div class="vyra-profile-face"><img ${safeImg(w.profileImage,fallbackProfile)}></div><div class="vyra-gift-face"><img ${safeImg(w.giftImage,fallbackGift)}></div></div><div class="topgift-copy"><strong style="font-size:${w.dataSize||20}px;color:${w.dataColor||'#fff'}">${VyraSafe.text(w.dataName,'@StreamQueen')}</strong><em style="display:${w.showDataValue===false?'none':'block'};color:${w.valueColor||w.accent||'#d9a441'}">◉ ${VyraSafe.text(w.dataValue,'44 999')}</em></div>${selected===w.id?'<span class="resize-handle">↘</span>':''}</div>`};

  socialGoalHtml=function(w){let live=window.VyraGoals?.read?.(w.id)||null,current=live?live.value:+(w.goalCurrent??658),target=live?live.target:Math.max(1,+(w.goalTarget||1000)),pct=Math.min(100,Math.round(current/target*100)),kind=w.goalKind||'followers',icon=kind==='likes'?'♥':'＋',model=w.goalModel||'crystal',frames={'rose-frame':{f:'rose-crystal-frame.webp',fil:[800,800],konst:[4,128,793,486],stav:[20.55,20.55,43.42,16.26]},'heart-frame':{f:'pink-crown-frame.webp',fil:[800,800],konst:[10,104,780,530],stav:[14.62,14.62,39.43,16.23]},'sapphire-frame':{f:'sapphire-dragon-frame.webp',fil:[800,533],konst:[1,6,794,520],stav:[16.75,16.12,42.5,14.04]},'azure-frame':{f:'azure-wing-frame.webp',fil:[800,800],konst:[0,79,800,565],stav:[18.13,18.13,51.33,12.21]}},ram=frames[model],frame=ram&&ram.f,frameArt=ram?`<img class="goal-frame-art" src="assets/goal-frames/${ram.f}" alt="">`:'',_kA=ram?ram.konst[2]/ram.konst[3]:0,_pk=ram?.69/_kA:0,_p=n=>n.toFixed(3),ramVars=ram?`;--ramA:${_kA.toFixed(4)};--ramBB:${_p(100*ram.fil[0]/ram.konst[2])}%;--ramBH:${_p(100*ram.fil[1]/ram.konst[3])}%;--ramBV:${_p(-100*ram.konst[0]/ram.konst[2])}%;--ramBO:${_p(-100*ram.konst[1]/ram.konst[3])}%;--ramBHP:${_p(100*_pk*ram.fil[1]/ram.konst[3])}%;--ramBOP:${_p(-100*_pk*ram.konst[1]/ram.konst[3])}%;--stavV:${ram.stav[0]}%;--stavH:${ram.stav[1]}%;--stavT:${ram.stav[2]}%;--stavHojd:${ram.stav[3]}%;--stavPT:${_p(ram.stav[2]*_pk)}%;--stavPHojd:${_p(ram.stav[3]*_pk)}%`:'';return `<div data-goal="social" class="widget social-goal premium-goal goal-${model}${frame?' goal-framed':''} goal-${w.goalOrientation||'landscape'} goal-kind-${kind}${selected===w.id?' selected':''}" data-id="${w.id}" style="left:${w.x}px;top:${w.y}px;width:${w.width||(w.goalOrientation==='portrait'?260:520)}px;--goal-a:${w.goalColor||'#24d8df'};--goal-b:${w.goalColor2||'#c34ee8'};--goal-pct:${pct};--goal-text-size:${w.goalTextSize||18}px;--goal-glow:${w.goalGlow??45}%;zoom:${w.widgetScale||1}${ramVars}">${frameArt}<div class="goal-icon">${icon}</div><div class="goal-copy"><h3>${w.goalTitle||(kind==='likes'?'LIKE GOAL':'FOLLOWER GOAL')}</h3><strong><b data-goal-value>${current.toLocaleString('sv-SE')}</b> <span>/</span> <b data-goal-target>${target.toLocaleString('sv-SE')}</b></strong><small data-goal-pct>${pct}% KLART</small></div><div class="goal-track" style="--fill:${pct}%"><i data-goal-fill></i><b></b><b></b><b></b><b></b><b></b><b></b></div>${w.goalShowLatest===false?'':`<em>+1 ${w.goalLatestName||'@NOVA'}</em>`}${selected===w.id?'<span class="resize-handle">↘</span>':''}</div>`};

  function position(w,def){return `<div class="property-group"><h4>POSITION & STORLEK</h4><div class="property-grid"><label>X<input id="propX" type="number" value="${w.x||0}"></label><label>Y<input id="propY" type="number" value="${w.y||0}"></label><label>Bredd<input id="propWidth" type="number" min="120" max="1200" value="${w.width||def}"></label><label>Lager<input id="propLayer" type="number" value="${w.layer||1}"></label></div></div>`}
  const oldProps=props;
  props=function(){let w=liveWidget(selected);if(!w)return oldProps();let hidden=`<div hidden><input id="pt" value="${w.title||''}"><input id="pv" value=""></div>`;
    if(w.type==='templateTopStreak')return `<h3>VYRA TOP STREAK</h3><div class="template-badge">7 PREMIUM · TIKTOK-SÄKER</div>${hidden}<div class="property-group"><h4>INNEHÅLL</h4><label>Stil<select id="pfStreakStyle">${Object.entries(STREAKS).map(([id,[n]])=>`<option value="${id}" ${w.streakTheme===id?'selected':''}>${n}</option>`).join('')}</select></label><label>Profilbild<input id="pfStreakProfile" value="${VyraSafe.url(w.profileImage,fallbackProfile)}"></label><label>Gåvobild<input id="pfStreakGift" value="${VyraSafe.url(w.giftImage,fallbackGift)}"></label><label>Användarnamn<input id="pfStreakName" value="${VyraSafe.text(w.dataName,'@StreamQueen')}"></label><label>Streak<input id="pfStreakValue" type="number" min="1" value="${VyraSafe.num(w.dataValue,18)}"></label></div><div class="property-group"><h4>DESIGN</h4><label>Accent<input id="pfStreakColor" type="color" value="${w.accent||'#d9a441'}"></label><label class="range-label">Profil/gåva <b>${w.giftSize||64}px</b><input id="pfStreakSize" type="range" min="36" max="130" value="${w.giftSize||64}"></label><label class="range-label">Rörelse <b>${w.streakSpeed||1}×</b><input id="pfStreakSpeed" type="range" min=".5" max="2" step=".1" value="${w.streakSpeed||1}"></label><label class="range-label">Ljus <b>${w.streakGlow??50}%</b><input id="pfStreakGlow" type="range" min="0" max="100" value="${w.streakGlow??50}"></label><button id="pfTestStreak">▶ Testa flip</button></div>${position(w,520)}<button class="delete" id="del">Ta bort</button>`;
    if(w.type==='templateTopGift')return `<h3>VYRA TOP GIFTER</h3><div class="template-badge">21 DESIGNVAL · LIVE</div>${hidden}<div class="property-group"><h4>INNEHÅLL</h4><label>Stil<select id="pfTopGiftStyle">${Object.entries(TOP_GIFTS).map(([id,n])=>`<option value="${id}" ${w.theme===id?'selected':''}>${n}</option>`).join('')}</select></label><label>Profilbild<input id="pfTopGiftProfile" value="${VyraSafe.url(w.profileImage,fallbackProfile)}"></label><label>Gåvobild<input id="pfTopGiftGift" value="${VyraSafe.url(w.giftImage,fallbackGift)}"></label><label>Användarnamn<input id="pfTopGiftName" value="${VyraSafe.text(w.dataName,'@StreamQueen')}"></label><label>Coins<input id="pfTopGiftCoins" value="${VyraSafe.text(w.dataValue,'44 999')}"></label></div><div class="property-group"><h4>DESIGN</h4><label>Accent<input id="pfTopGiftColor" type="color" value="${w.accent||'#d9a441'}"></label><label class="range-label">Profil/gåva <b>${w.giftSize||110}px</b><input id="pfTopGiftSize" type="range" min="48" max="220" value="${w.giftSize||110}"></label><label class="range-label">Text <b>${w.dataSize||20}px</b><input id="pfTopGiftText" type="range" min="12" max="48" value="${w.dataSize||20}"></label><label class="range-label">Flipphastighet <b>${w.topGiftFlipSpeed||1}×</b><input id="pfTopGiftSpeed" type="range" min=".5" max="2" step=".1" value="${w.topGiftFlipSpeed||1}"></label><label class="range-label">Ljus <b>${w.topGiftGlow??55}%</b><input id="pfTopGiftGlow" type="range" min="0" max="100" value="${w.topGiftGlow??55}"></label><button id="pfTestTopGift">▶ Testa profil → gåva</button></div>${position(w,340)}<button class="delete" id="del">Ta bort</button>`;
    if(w.type==='templateSocialGoal')return `<h3>${w.goalKind==='likes'?'LIKE':'FOLLOWER'} GOAL</h3><div class="template-badge">7 PREMIUMDESIGNER</div>${hidden}<div class="property-group"><h4>INNEHÅLL</h4><label>Design<select id="pfGoalModel">${Object.entries(GOALS).map(([id,n])=>`<option value="${id}" ${w.goalModel===id?'selected':''}>${n}</option>`).join('')}</select></label><label>Rubrik<input id="pfGoalTitle" value="${w.goalTitle||(w.goalKind==='likes'?'LIKE GOAL':'FOLLOWER GOAL')}"></label><div class="property-grid"><label>Nuvarande<input id="pfGoalCurrent" type="number" min="0" value="${w.goalCurrent??658}"></label><label>Mål<input id="pfGoalTarget" type="number" min="1" value="${w.goalTarget||1000}"></label></div><label>Senaste namn<input id="pfGoalLatest" value="${w.goalLatestName||'@NOVA'}"></label><div class="switch-row one"><label><input id="pfGoalShowLatest" type="checkbox" ${w.goalShowLatest===false?'':'checked'}> Visa +1 namn</label></div></div><div class="property-group"><h4>DESIGN</h4><label>Orientering<select id="pfGoalOrientation"><option value="landscape" ${w.goalOrientation!=='portrait'?'selected':''}>Liggande</option><option value="portrait" ${w.goalOrientation==='portrait'?'selected':''}>Stående</option></select></label><div class="color-grid"><label>Färg 1<input id="pfGoalColor" type="color" value="${w.goalColor||'#24d8df'}"></label><label>Färg 2<input id="pfGoalColor2" type="color" value="${w.goalColor2||'#c34ee8'}"></label></div><label class="range-label">Text <b>${w.goalTextSize||18}px</b><input id="pfGoalTextSize" type="range" min="11" max="38" value="${w.goalTextSize||18}"></label><label class="range-label">Ljus <b>${w.goalGlow??45}%</b><input id="pfGoalGlow" type="range" min="0" max="100" value="${w.goalGlow??45}"></label><button id="pfGoalPlus">+1 Test</button><button id="pfGoalComplete">Testa 100%</button></div>${position(w,w.goalOrientation==='portrait'?260:520)}<button class="delete" id="del">Ta bort</button>`;
    return oldProps();
  };

  // Startvarde och Mal ar serverdata. De PATCH:as, och legacyfaltet speglas forst nar servern
  // svarat - runtimen sköter den speglingen via sessionsagaren.
  function bindGoalControl(selector,w,field){const el=document.querySelector(selector);if(!el)return;
    el.onchange=async e=>{const value=Math.trunc(Number(e.target.value));
      const out=field==='baseline'?await window.VyraGoals?.patchBaseline?.(w.id,value)
                                  :await window.VyraGoals?.patchTarget?.(w.id,value);
      if(!out||!out.ok){e.target.value=field==='baseline'?(w.goalCurrent??0):(w.goalTarget||1000);
        toast?.('Kunde inte spara malet')}}}
  const oldBind=bind;
  bind=function(){oldBind();if(view!=='editor')return;let w=liveWidget(selected);if(!w)return;let set=(id,key,num=false)=>{let el=document.querySelector(id);if(!el)return;const las=e=>num?+e.target.value:e.target.value;el.oninput=e=>vyraLivePatch(w,el,key,las(e));el.onchange=e=>{w[key]=las(e);save();vyraRenderKeepingPanel()}};
    if(w.type==='templateTopStreak'){set('#pfStreakStyle','streakTheme');set('#pfStreakProfile','profileImage');set('#pfStreakGift','giftImage');set('#pfStreakName','dataName');set('#pfStreakValue','dataValue',true);set('#pfStreakColor','accent');set('#pfStreakSize','giftSize',true);set('#pfStreakSpeed','streakSpeed',true);set('#pfStreakGlow','streakGlow',true);document.querySelector('#pfTestStreak')?.addEventListener('click',()=>{let e=document.querySelector(`[data-id="${w.id}"]`);e.classList.remove('hit');void e.offsetWidth;e.classList.add('hit')})}
    if(w.type==='templateTopGift'){set('#pfTopGiftStyle','theme');set('#pfTopGiftProfile','profileImage');set('#pfTopGiftGift','giftImage');set('#pfTopGiftName','dataName');set('#pfTopGiftCoins','dataValue');set('#pfTopGiftColor','accent');set('#pfTopGiftSize','giftSize',true);set('#pfTopGiftText','dataSize',true);set('#pfTopGiftSpeed','topGiftFlipSpeed',true);set('#pfTopGiftGlow','topGiftGlow',true);document.querySelector('#pfTestTopGift')?.addEventListener('click',()=>{let e=document.querySelector(`[data-id="${w.id}"]`);e.classList.remove('play');void e.offsetWidth;e.classList.add('play')})}
    if(w.type==='templateSocialGoal'){set('#pfGoalModel','goalModel');set('#pfGoalTitle','goalTitle');bindGoalControl('#pfGoalCurrent',w,'baseline');bindGoalControl('#pfGoalTarget',w,'target');set('#pfGoalLatest','goalLatestName');set('#pfGoalColor','goalColor');set('#pfGoalColor2','goalColor2');set('#pfGoalTextSize','goalTextSize',true);set('#pfGoalGlow','goalGlow',true);let show=document.querySelector('#pfGoalShowLatest');if(show)show.onchange=e=>{w.goalShowLatest=e.target.checked;save();render()};let orientation=document.querySelector('#pfGoalOrientation');if(orientation)orientation.onchange=e=>{w.goalOrientation=e.target.value;w.width=e.target.value==='portrait'?260:520;save();render()};/* Testknapparna ar designhjalp, inte data. De far darfor aldrig rora ett riktigt mal: de gar via runtimens flyktiga forhandsvisning, som nasta riktiga frame eller snapshot skriver over. En lokal raknare i widgetobjektet skulle daremot sparas och bli omojlig att skilja fran verklig progress. *//* Forhandsvisningen borjar dar widgeten FAKTISKT star, inte pa noll. Utan ett livemal ar det w.goalCurrent renderaren visar, och en +1-knapp som hoppade till 1 fran 658 sag ut som att den nollstallde malet. Samma fallback som renderaren, ord for ord. */const goalBase=()=>{const live=window.VyraGoals?.read?.(w.id)||null;return{value:live?live.value:+(w.goalCurrent??658),target:live?live.target:Math.max(1,+(w.goalTarget||1000))}};/* Egen raknare for forhandsvisningen: read() ser inte patchen, sa utan den skulle varje klick rakna fran samma utgangsvarde och +1 aldrig ga langre an ett steg. Den lever bara sa lange panelen ar bunden och nollstalls vid nasta render — inget av den nar state eller servern. */let preview=null;document.querySelector('#pfGoalPlus')?.addEventListener('click',()=>{const base=goalBase();const value=(preview??base.value)+1;preview=value;window.VyraGoalDom?.patch?.(w.id,{value,target:base.target})});document.querySelector('#pfGoalComplete')?.addEventListener('click',()=>{const base=goalBase();preview=base.target;window.VyraGoalDom?.patch?.(w.id,{value:base.target,target:base.target})})}
  };

  const oldCatalogBind=bind;
  bind=function(){oldCatalogBind();if(view!=='editor'&&view!=='overlay')return;let streak=document.querySelector('.streak-template-section');if(streak&&!streak.dataset.finalPremium){streak.dataset.finalPremium='1';streak.insertAdjacentHTML('beforeend','<h4>VYRA TOP STREAK · PREMIUM</h4><div class="streak-style-grid">'+Object.entries(STREAKS).map(([id,[n,c]])=>`<button data-pf-streak="${id}" style="--swatch:${c}"><i>↗</i><span><b>${n}</b><small>Profil → gåva · × streak</small></span></button>`).join('')+'</div>');streak.querySelectorAll('[data-pf-streak]').forEach(b=>{/* Nyckeln pa knappen ar det som gor designen matbar, forhandsvisningsbar och aterskapbar: overlay-preview bygger sin miniatyr ur den, katalogtestet raknar unika widgets ur den, och en sparad layout identifierar sin variant med createdFrom. Widgeten byggs nu ur fabriken i stallet for handknackt har - ett test jamfor falt for falt mot den gamla formen. */const catalogKey='catalog:topstreak:premium:'+b.dataset.pfStreak;b.dataset.catalogKey=catalogKey;b.onclick=()=>{const created=VyraWidgets.create(catalogKey);state.widgets=state.widgets.filter(w=>w.type!=='templateTopStreak');state.widgets.push(created);selected=created.id;save();render()}})}
    let gifts=document.querySelector('.prototype-section');if(gifts&&!gifts.dataset.finalPremium){gifts.dataset.finalPremium='1';gifts.innerHTML='<h4>TOP GIFTER · DESIGNVAL</h4><div class="template-style-grid">'+Object.entries(TOP_GIFTS).map(([id,n])=>`<button data-pf-topgift="${id}"><i>◆</i><span><b>${n}</b><small>Profil → gåva · inga gåvonamn</small></span></button>`).join('')+'</div>';gifts.querySelectorAll('[data-pf-topgift]').forEach(b=>{const catalogKey='catalog:topgift:premium:'+b.dataset.pfTopgift;b.dataset.catalogKey=catalogKey;b.onclick=()=>{const created=VyraWidgets.create(catalogKey);state.widgets=state.widgets.filter(w=>w.type!=='templateTopGift');state.widgets.push(created);selected=created.id;save();render()}})}
    let goals=document.querySelector('.social-goal-template-section');if(goals&&!goals.dataset.finalPremium){goals.dataset.finalPremium='1';goals.querySelectorAll('small').forEach(s=>s.textContent='11 premiumdesigner · 16 ramval');let extra=[['rose-frame','Rose Crystal Frame'],['heart-frame','Royal Heart Frame'],['sapphire-frame','Sapphire Dragon Frame'],['azure-frame','Azure Crown Frame']];goals.insertAdjacentHTML('beforeend','<div class="template-style-grid goal-frame-catalog">'+['followers','likes'].flatMap(kind=>extra.flatMap(([model,label])=>['landscape','portrait'].map(orient=>`<button data-goal-frame="${model}" data-goal-kind="${kind}" data-goal-orient="${orient}"><i>◈</i><span><b>${kind==='likes'?'Like':'Follower'} · ${label}</b><small>${orient==='portrait'?'Stående':'Liggande'} · transparent ram</small></span></button>`))).join('')+'</div>');goals.querySelectorAll('[data-goal-frame]').forEach(b=>{const catalogKey='catalog:socialgoal:'+b.dataset.goalKind+':'+b.dataset.goalFrame+':'+(b.dataset.goalOrient||'landscape');b.dataset.catalogKey=catalogKey;b.onclick=()=>{const created=VyraWidgets.create(catalogKey);state.widgets.push(created);selected=created.id;save();render()}})}
  };
})();
