$root=[IO.Path]::GetFullPath($PSScriptRoot)
$listener=[Net.HttpListener]::new();$listener.Prefixes.Add('http://127.0.0.1:4173/');$listener.Prefixes.Add('http://localhost:4173/');$listener.Start()
$events=[Collections.Generic.List[object]]::new();$seenEvents=@{};$requestBuckets=@{};$connection=[ordered]@{connected=$false;username='';mode='demo';state='idle';roomId='';heartbeat=0;reconnectAttempt=0;updated=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()}
$types=@{'.html'='text/html; charset=utf-8';'.css'='text/css; charset=utf-8';'.js'='text/javascript; charset=utf-8';'.json'='application/json; charset=utf-8';'.png'='image/png';'.jpg'='image/jpeg';'.jpeg'='image/jpeg';'.mp4'='video/mp4';'.svg'='image/svg+xml';'.webp'='image/webp';'.woff2'='font/woff2'}
function Send-Bytes($r,[byte[]]$b,[string]$t='application/json; charset=utf-8',[int]$s=200){$r.StatusCode=$s;$r.ContentType=$t;$r.ContentLength64=$b.Length;$r.AddHeader('Cache-Control','no-store');$r.OutputStream.Write($b,0,$b.Length);$r.Close()}
function Send-Json($r,$v,[int]$s=200){Send-Bytes $r ([Text.Encoding]::UTF8.GetBytes(($v|ConvertTo-Json -Depth 12 -Compress))) 'application/json; charset=utf-8' $s}
$utf8NoBom=[Text.UTF8Encoding]::new($false)
$backupDir=Join-Path $root '.vyra-backups'
function Write-Atomic([string]$file,[string]$raw){$tmp=$file+'.tmp';[IO.File]::WriteAllText($tmp,$raw,$utf8NoBom);Move-Item -LiteralPath $tmp -Destination $file -Force}
function Read-RawBody($q){$ms=[IO.MemoryStream]::new();$q.InputStream.CopyTo($ms);$bytes=$ms.ToArray();$ms.Dispose();if(!$bytes.Length){return ''};return [Text.Encoding]::UTF8.GetString($bytes)}
function Read-Json($q){$raw=Read-RawBody $q;if(!$raw){return @{}};return($raw|ConvertFrom-Json)}
function Clean-Text($v,[int]$max){$s=([string]$v)-replace '[\x00-\x08\x0B\x0C\x0E-\x1F\x7F<>]','';if($s.Length -gt $max){$s=$s.Substring(0,$max)};return $s}
function Clean-Url($v){$s=Clean-Text $v 2048;if($s -match '^(https?://|data:image/(png|jpeg|webp|gif);base64,)'){return $s};return ''}
function Clamp-Number($v,[double]$min,[double]$max){$n=0.0;if(![double]::TryParse([string]$v,[ref]$n)){return 0};return [Math]::Min($max,[Math]::Max($min,$n))}
Write-Host '';Write-Host 'VYRA Live Server ar igang' -ForegroundColor Magenta;Write-Host 'Studio:  http://127.0.0.1:4173/studio.html';Write-Host 'Overlay: http://127.0.0.1:4173/overlay.html';Write-Host 'Stoppa med Ctrl+C'
try{while($listener.IsListening){$c=$listener.GetContext();$q=$c.Request;$r=$c.Response;$p=$q.Url.AbsolutePath
 try{
  $r.AddHeader('X-Content-Type-Options','nosniff');$r.AddHeader('Referrer-Policy','no-referrer');$r.AddHeader('Cross-Origin-Resource-Policy','same-origin');$r.AddHeader('X-Frame-Options','SAMEORIGIN')
  if($p.StartsWith('/api/') -and $q.HttpMethod -ne 'GET'){$origin=[string]$q.Headers['Origin'];if($origin -and $origin -ne 'http://127.0.0.1:4173' -and $origin -ne 'http://localhost:4173'){Send-Json $r @{ok=$false;error='Origin nekad'} 403;continue}}
  if($p.StartsWith('/api/')){$ip=[string]$q.RemoteEndPoint.Address;$nowRate=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();if(!$requestBuckets.ContainsKey($ip)-or $nowRate-$requestBuckets[$ip].at -ge 1000){$requestBuckets[$ip]=@{at=$nowRate;count=0}};$requestBuckets[$ip].count++;if($requestBuckets[$ip].count -gt 2500){Send-Json $r @{ok=$false;error='För många anrop'} 429;continue}}
  if($q.HttpMethod -ne 'GET'){$limit=if($p -like '/api/state*'){5MB}else{64KB};if($q.ContentLength64 -gt $limit){Send-Json $r @{ok=$false;error='Payload för stor'} 413;continue}}
  if($p -eq '/api/status'){$now=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();if($connection.connected -and $connection.heartbeat -and $now-$connection.heartbeat -gt 15000){$connection.connected=$false;$connection.state='stale';$connection.updated=$now};Send-Json $r ([ordered]@{ok=$true;server='VYRA Live Server';connection=$connection;lastEventId=if($events.Count){$events[$events.Count-1].id}else{0}});continue}
  if($p -eq '/api/connect' -and $q.HttpMethod -eq 'POST'){$d=Read-Json $q;$now=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();$connection.connected=$true;$connection.username=[string]$d.username;$connection.mode='connector-ready';$connection.state='live';$connection.roomId=[string]$d.roomId;$connection.heartbeat=$now;$connection.reconnectAttempt=0;$connection.updated=$now;Send-Json $r @{ok=$true;connection=$connection;message='Redo for LIVE-events'};continue}
  if($p -eq '/api/disconnect' -and $q.HttpMethod -eq 'POST'){$d=Read-Json $q;$connection.connected=$false;$connection.state=if($d.retryInMs){'reconnecting'}else{'disconnected'};$connection.reconnectAttempt=[int]$d.reconnectAttempt;$connection.retryInMs=[int]$d.retryInMs;$connection.reason=[string]$d.reason;$connection.updated=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();Send-Json $r @{ok=$true;connection=$connection};continue}
  if($p -eq '/api/heartbeat' -and $q.HttpMethod -eq 'POST'){$d=Read-Json $q;$now=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();$connection.connected=$true;$connection.state='live';$connection.heartbeat=$now;$connection.updated=$now;$connection.username=[string]$d.username;$connection.roomId=[string]$d.roomId;$connection.reconnectAttempt=[int]$d.reconnectAttempt;Send-Json $r @{ok=$true;connection=$connection};continue}
  if($p -eq '/api/events' -and $q.HttpMethod -eq 'GET'){$after=0;[void][long]::TryParse($q.QueryString['after'],[ref]$after);Send-Json $r @{ok=$true;events=@($events|Where-Object{$_.id -gt $after})};continue}
  if($p -eq '/api/events' -and $q.HttpMethod -eq 'POST'){$d=Read-Json $q;$type=(Clean-Text $d.type 64)-replace '[^a-zA-Z0-9_:-]','';if(!$type){Send-Json $r @{ok=$false;error='Eventtyp saknas'} 400;continue};$id=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();$key=Clean-Text $d.eventKey 200;@($seenEvents.Keys)|Where-Object{$id-[long]$seenEvents[$_] -gt 120000}|ForEach-Object{$seenEvents.Remove($_)};if($key -and $seenEvents.ContainsKey($key)){Send-Json $r @{ok=$true;duplicate=$true;eventKey=$key};continue};if($key){$seenEvents[$key]=$id};while($events.Count -and $events[$events.Count-1].id -ge $id){$id++};$e=[ordered]@{id=$id;type=$type;username=Clean-Text $d.username 100;name=Clean-Text $d.name 500;profileImage=Clean-Url $d.profileImage;giftName=Clean-Text $d.giftName 160;giftImage=Clean-Url $d.giftImage;coins=Clamp-Number $d.coins 0 1000000000;count=Clamp-Number $d.count 0 10000000;multiplier=Clamp-Number $d.multiplier 0 100;points=Clamp-Number $d.points 0 1000000000000;level=Clamp-Number $d.level 0 10000;score=Clamp-Number $d.score 0 1000000000000;scoreUs=Clamp-Number $d.scoreUs 0 1000000000000;scoreThem=Clamp-Number $d.scoreThem 0 1000000000000;ourScore=Clamp-Number $d.ourScore 0 1000000000000;opponentScore=Clamp-Number $d.opponentScore 0 1000000000000;eventKey=$key;source=Clean-Text $d.source 64;timestamp=$id};$events.Add($e);while($events.Count -gt 5000){$events.RemoveAt(0)};Send-Json $r @{ok=$true;event=$e};continue}
  if($p -eq '/api/state' -and $q.HttpMethod -eq 'GET'){$backupFile=Join-Path $root 'vyra-state-backup.json';if(Test-Path -LiteralPath $backupFile){Send-Bytes $r ([IO.File]::ReadAllBytes($backupFile)) 'application/json; charset=utf-8'}else{Send-Json $r @{ok=$false;error='Ingen backup sparad an'} 404};continue}
  if($p -eq '/api/state' -and $q.HttpMethod -eq 'POST'){$raw=Read-RawBody $q;if($raw){$null=$raw|ConvertFrom-Json;Write-Atomic (Join-Path $root 'vyra-state-backup.json') $raw};Send-Json $r @{ok=$true};continue}
  if($p -eq '/api/state/versions' -and $q.HttpMethod -eq 'GET'){$versions=@();if(Test-Path $backupDir){$versions=@(Get-ChildItem -LiteralPath $backupDir -Filter 'state-*.json'|Sort-Object Name -Descending|ForEach-Object{$dto=[DateTimeOffset]$_.LastWriteTimeUtc;@{id=$_.BaseName.Substring(6);createdAt=$dto.ToUnixTimeMilliseconds();size=$_.Length}})};Send-Json $r @{ok=$true;versions=$versions};continue}
  if($p -eq '/api/state/version' -and $q.HttpMethod -eq 'GET'){$id=[string]$q.QueryString['id'];if($id -notmatch '^\d+$'){Send-Json $r @{ok=$false;error='Ogiltig version'} 400;continue};$file=Join-Path $backupDir ('state-'+$id+'.json');if(!(Test-Path $file)){Send-Json $r @{ok=$false;error='Version saknas'} 404;continue};Send-Bytes $r ([IO.File]::ReadAllBytes($file)) 'application/json; charset=utf-8';continue}
  if($p -eq '/api/state/version' -and $q.HttpMethod -eq 'POST'){$raw=Read-RawBody $q;$parsed=$raw|ConvertFrom-Json;if($null -eq $parsed.widgets){Send-Json $r @{ok=$false;error='Ogiltig VYRA-state'} 400;continue};if(!(Test-Path $backupDir)){New-Item -ItemType Directory -Path $backupDir|Out-Null};$id=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();Write-Atomic (Join-Path $backupDir ('state-'+$id+'.json')) $raw;@(Get-ChildItem -LiteralPath $backupDir -Filter 'state-*.json'|Sort-Object Name -Descending|Select-Object -Skip 20)|Remove-Item -Force;Send-Json $r @{ok=$true;id=[string]$id};continue}
  if($q.HttpMethod -ne 'GET'){Send-Json $r @{ok=$false;error='Method not allowed'} 405;continue}
  $rel=[Uri]::UnescapeDataString($p).TrimStart('/');if(!$rel){$rel='index.html'};$file=[IO.Path]::GetFullPath((Join-Path $root $rel));if(!$file.StartsWith($root,[StringComparison]::OrdinalIgnoreCase) -or !(Test-Path -LiteralPath $file -PathType Leaf)){Send-Json $r @{ok=$false;error='Hittades inte'} 404;continue};$body=[IO.File]::ReadAllBytes($file);$ext=[IO.Path]::GetExtension($file).ToLowerInvariant();$type=if($types.ContainsKey($ext)){$types[$ext]}else{'application/octet-stream'};Send-Bytes $r $body $type
 }catch{try{Send-Json $r @{ok=$false;error=$_.Exception.Message} 500}catch{}}
}}finally{$listener.Stop();$listener.Close()}
