(function(root){
  'use strict';
  const PERIODS=new Set(['7d','30d','90d','all']);
  let mounted=null,period='30d',generation=0,retryTimer=0;
  const number=value=>(Number(value)||0).toLocaleString('sv-SE');
  const text=(node,value)=>{if(node)node.textContent=String(value)};
  function status(message,error=false){const node=mounted?.querySelector('[data-stats-status]');if(!node)return;text(node,message);node.classList.toggle('error',error)}
  function totals(data){for(const key of ['gifts','diamonds','likes'])text(mounted?.querySelector(`[data-stats-total="${key}"]`),number(data?.totalt?.[key]))}
  function chart(days){const rootNode=mounted?.querySelector('[data-stats-chart]');if(!rootNode)return;rootNode.replaceChildren();const rows=Array.isArray(days)?days.slice(-30):[];if(!rows.length){const empty=document.createElement('div');empty.className='statistics-empty';empty.textContent='Ingen livedata i den valda perioden ännu.';rootNode.append(empty);return}const max=Math.max(1,...rows.map(row=>Number(row.diamonds)||0));rows.forEach((row,index)=>{const bar=document.createElement('div');bar.className='statistics-bar';bar.style.setProperty('--bar-height',`${Math.max(3,Math.round((Number(row.diamonds)||0)/max*100))}%`);const date=String(row.dag||'');bar.title=`${date}: ${number(row.diamonds)} diamanter · ${number(row.gifts)} gåvor · ${number(row.likes)} likes`;if(rows.length<=14||index%Math.ceil(rows.length/10)===0){const label=document.createElement('span');label.textContent=date.slice(5);bar.append(label)}rootNode.append(bar)})}
  function supporters(rows){const list=mounted?.querySelector('[data-stats-supporters]');if(!list)return;list.replaceChildren();const data=Array.isArray(rows)?rows.slice(0,10):[];if(!data.length){const empty=document.createElement('li');empty.className='statistics-empty';empty.textContent='Inga supportrar registrerade ännu.';list.append(empty);return}data.forEach((giver,index)=>{const item=document.createElement('li'),rank=document.createElement('i');rank.textContent=String(index+1);let avatar;if(/^https?:\/\//.test(String(giver.avatar||''))){avatar=document.createElement('img');avatar.src=giver.avatar;avatar.alt='';avatar.loading='lazy'}else{avatar=document.createElement('span');avatar.className='statistics-avatar';avatar.textContent=String(giver.namn||'?').slice(0,1).toUpperCase()}const copy=document.createElement('span'),name=document.createElement('b'),detail=document.createElement('small'),value=document.createElement('strong');name.textContent=String(giver.namn||'Okänd');detail.textContent=giver.bastaGava?.namn?`Bästa gåva: ${giver.bastaGava.namn}`:`${number(giver.gifts)} gåvor`;value.textContent=`${number(giver.diamonds)} 💎`;copy.append(name,detail);item.append(rank,avatar,copy,value);list.append(item)})}
  function paint(data){totals(data);chart(data?.dagar);supporters(data?.toppGivare);if(data?.fel)return status('Statistiken kunde inte hämtas just nu. Försök igen om en stund.',true);if(!data?.konto)return status('Ingen TikTok är ansluten. Historiken börjar när du sänder med VYRA Desktop.');if(!data?.forstaDagen)return status('Ingen historik ännu. Den börjar byggas vid nästa sändning.');status(period==='all'?`All statistik sedan ${data.forstaDagen}.`:`Visar ${period.replace('d',' dagar')} · första registrerade livedag ${data.forstaDagen}.`)}
  async function load(){if(!mounted||!document.contains(mounted))return;const call=++generation;mounted.classList.add('is-loading');status('Hämtar din statistik…');const workspace=root.VyraCloudSync?.current?.()?.workspace;if(!workspace?.id||!root.VyraAuth?.api){mounted.classList.remove('is-loading');status('Väntar på ditt konto och din arbetsyta…');clearTimeout(retryTimer);retryTimer=setTimeout(()=>{if(mounted&&document.contains(mounted))load()},700);return}try{const data=await root.VyraAuth.api(`/api/workspaces/${encodeURIComponent(workspace.id)}/stats?period=${encodeURIComponent(period)}`);if(call===generation&&mounted&&document.contains(mounted))paint(data||{})}catch(error){if(call===generation&&mounted&&document.contains(mounted))paint({fel:true,totalt:{gifts:0,diamonds:0,likes:0},dagar:[],toppGivare:[]})}finally{if(call===generation&&mounted)mounted.classList.remove('is-loading')}}
  function mount(){const page=document.querySelector('[data-statistics-page]');if(!page||page===mounted)return;mounted=page;period='30d';page.querySelectorAll('[data-stats-period]').forEach(button=>button.addEventListener('click',()=>{const next=button.dataset.statsPeriod;if(!PERIODS.has(next)||next===period)return;period=next;page.querySelectorAll('[data-stats-period]').forEach(item=>item.classList.toggle('active',item===button));load()}));load()}
  new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});
  root.addEventListener('vyra-auth-ready',()=>mounted&&load());
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
  root.VyraStatistics={mount,load};
})(typeof window!=='undefined'?window:globalThis);
