(function(root){
  'use strict';
  // Backup is a Studio feature. The overlay authenticates with ?access=<token> and has no session
  // cookie, so every /api/state call it makes is a guaranteed 401 — and the 3s loop below retried
  // forever: two failed POSTs per tick, for the whole broadcast, on the machine that is streaming.
  // An overlay also has no layout of its own to protect, and must never write one back. So nothing
  // in this file may start in overlay mode: no fetch, no timer, no restore.
  const VYRA_PARAMS=new URLSearchParams(location.search);
  if(VYRA_PARAMS.has('overlay')||VYRA_PARAMS.has('access'))return;
  const STATE_KEY='vyra-state', EXTRA_KEYS=['vyra-extras','vyra-action-event-v2','vyra-favorite-widgets','vyra-wishlist','vyra-overlay-resolution'], AUTO_VERSION_MS=5*60*1000;
  let lastSynced=localStorage.getItem(STATE_KEY),lastVersioned=lastSynced,lastVersionAt=0,busy=false;
  function parse(raw,fallback={}){try{return JSON.parse(raw)}catch{return fallback}}
  function sanitizeWidget(w){if(!w||typeof w!=='object'||!w.id)return null;return {...w,title:w.title||w.type||'Widget'}}
  function primary(){const value=parse(localStorage.getItem(STATE_KEY),'');return value&&Array.isArray(value.widgets)?value:null}
  function packageState(){const value=primary();if(!value)return null;const storage={};EXTRA_KEYS.forEach(k=>{const v=localStorage.getItem(k);if(v!=null)storage[k]=v});return {...value,__vyraBackup:{schema:1,createdAt:Date.now(),storage}}}
  function validate(data){return !!(data&&typeof data==='object'&&Array.isArray(data.widgets)&&data.widgets.every(w=>w&&typeof w==='object'&&w.id))}
  function apply(data){if(!validate(data))throw new Error('Backupen innehåller ingen giltig VYRA-layout');const clean={...data,widgets:data.widgets.map(sanitizeWidget).filter(Boolean)};const meta=clean.__vyraBackup;delete clean.__vyraBackup;localStorage.setItem(STATE_KEY,JSON.stringify(clean));Object.entries(meta?.storage||{}).forEach(([k,v])=>{if(EXTRA_KEYS.includes(k)&&typeof v==='string')localStorage.setItem(k,v)});if(typeof state==='object'&&state){Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,clean)};lastSynced=JSON.stringify(clean);lastVersioned=lastSynced;root.VyraActionEvent?.refresh?.();root.render?.();return clean.widgets.length}
  async function post(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:typeof data==='string'?data:JSON.stringify(data)});if(!r.ok)throw new Error((await r.json().catch(()=>null))?.error||'Serverfel '+r.status);return r.json()}
  async function syncLatest(){const data=packageState();if(!data)return;await post('/api/state',data)}
  async function createVersion(reason='Manuell'){if(busy)return;const data=packageState();if(!data)throw new Error('Ingen giltig layout att säkerhetskopiera');busy=true;try{const result=await post('/api/state/version',data);lastVersioned=localStorage.getItem(STATE_KEY);lastVersionAt=Date.now();root.toast?.(`${reason} backup skapad`);return result}finally{busy=false}}
  async function versions(){const r=await fetch('/api/state/versions',{cache:'no-store'});if(!r.ok)throw new Error('Kunde inte läsa versioner');return (await r.json()).versions||[]}
  async function restore(id){await createVersion('Säkerhets');const r=await fetch('/api/state/version?id='+encodeURIComponent(id),{cache:'no-store'});if(!r.ok)throw new Error('Versionen kunde inte läsas');const count=apply(await r.json());root.toast?.(`${count} widgets återställdes`)}
  function download(){const data=packageState();if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='VYRA-layout-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function importFile(file){const reader=new FileReader();reader.onload=async()=>{try{const data=JSON.parse(reader.result);if(!validate(data))throw new Error('Ogiltig VYRA-fil');await createVersion('Före import');const count=apply(data);await syncLatest();root.toast?.(`${count} widgets importerades`);document.querySelector('.vb-modal')?.remove()}catch(e){root.toast?.(e.message)}};reader.readAsText(file)}
  function date(v){return new Date(v).toLocaleString('sv-SE',{dateStyle:'short',timeStyle:'short'})}
  async function openManager(){document.querySelector('.vb-modal')?.remove();const modal=document.createElement('div');modal.className='vb-modal';modal.innerHTML='<section><header><div><small>BACKUP & ÅTERSTÄLLNING</small><h2>Versionshistorik</h2></div><button data-vb-close>×</button></header><div class="vb-actions"><button id="vbCreate" class="primary">Skapa version nu</button><button id="vbExport">Exportera JSON</button><label>Importera JSON<input id="vbImport" type="file" accept="application/json,.json"></label></div><div id="vbVersions" class="vb-versions"><p>Laddar versioner…</p></div><footer>Automatisk backup körs efter ändringar och högst var femte minut. De 20 senaste versionerna sparas.</footer></section>';document.body.append(modal);modal.querySelector('[data-vb-close]').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};modal.querySelector('#vbCreate').onclick=async()=>{try{await createVersion();await drawVersions(modal)}catch(e){root.toast?.(e.message)}};modal.querySelector('#vbExport').onclick=download;modal.querySelector('#vbImport').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);await drawVersions(modal)}
  async function drawVersions(modal){const host=modal.querySelector('#vbVersions');try{const list=await versions();host.innerHTML=list.length?list.map((v,i)=>`<article><span><b>${i===0?'Senaste version':'Tidigare version'}</b><small>${date(v.createdAt)} · ${Math.ceil(v.size/1024)} KB</small></span><button data-vb-restore="${v.id}">Återställ</button></article>`).join(''):'<p>Ingen versionshistorik ännu.</p>';host.querySelectorAll('[data-vb-restore]').forEach(b=>b.onclick=async()=>{if(!confirm('Återställa denna version? Nuvarande layout säkerhetskopieras först.'))return;try{await restore(b.dataset.vbRestore);modal.remove()}catch(e){root.toast?.(e.message)}})}catch(e){host.innerHTML='<p>Starta VYRA-servern för att använda versionshistorik.</p>'}}
  function injectSettings(){if(typeof view==='undefined'||view!=='settings')return;const card=document.querySelector('#view .settings-page');if(!card||card.querySelector('#openBackupManager'))return;const box=document.createElement('div');box.className='vb-settings';box.innerHTML='<span><b>Backup och versionshistorik</b><small>Automatiskt skydd för layout, widgets och automationer.</small></span><button id="openBackupManager">Hantera backup</button>';card.append(box);box.querySelector('button').onclick=openManager}
  document.addEventListener('click',e=>{if(e.target.closest?.('[data-view="settings"]'))setTimeout(injectSettings,80)});
  // lastVersionAt used to advance only on SUCCESS, so a backend that was down left the five-minute
  // gate permanently open: every tick with a changed layout fired another version POST. Stamping
  // the attempt instead means a failing backend costs one try per five minutes, not one per three
  // seconds, while a healthy one behaves exactly as before.
  setInterval(async()=>{const current=localStorage.getItem(STATE_KEY);if(!current||current===lastSynced)return;lastSynced=current;try{await syncLatest()}catch{}if(current!==lastVersioned&&Date.now()-lastVersionAt>=AUTO_VERSION_MS){lastVersionAt=Date.now();try{await createVersion('Automatisk')}catch{}}},3000);
  if(!primary())fetch('/api/state').then(r=>r.ok?r.json():null).then(data=>{if(validate(data)){const count=apply(data);console.log('[VYRA] Återställde '+count+' widgets från backup.')}}).catch(()=>{});else syncLatest().catch(()=>{});
  root.VyraBackup={createVersion,versions,restore,download,openManager,validate,packageState};
})(typeof window!=='undefined'?window:globalThis);
