'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function boot(reduced=false){
 const listeners=new Set(),events=new Map(),media=new Map();let clears=0;
 const gradient={addColorStop(){}};
 const ctx=new Proxy({createRadialGradient:()=>gradient,createLinearGradient:()=>gradient,clearRect(){clears++}}, {get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});
 const leaf=()=>({style:{setProperty(){}},textContent:''});
 const gifts=Array.from({length:4},()=>{const nodes={'.frame img':leaf(),'.count b':leaf(),'.goal-mark':leaf(),'.remaining':leaf(),'.meter i':leaf(),'canvas.live-aura':{width:360,height:396,getContext:()=>ctx}};return {style:leaf().style,clientWidth:140,querySelector:s=>nodes[s==='img'?'.frame img':s],querySelectorAll:s=>s==='.burst i'?Array.from({length:18},leaf):[]}});
 const heading=leaf();heading.clientWidth=600;
 const group={isConnected:true,clientWidth:608,closest:()=>null,querySelectorAll:s=>s==='.gift'?gifts:[heading]};
 const document={hidden:false,addEventListener:(k,f)=>events.set(k,f),removeEventListener:k=>events.delete(k)};
 const c={window:null,document,VFX:{Ticker:{subscribe:f=>{listeners.add(f);return()=>listeners.delete(f)}}},matchMedia:()=>({matches:reduced,addEventListener:(k,f)=>media.set(k,f),removeEventListener:k=>media.delete(k)}),addEventListener:(k,f)=>events.set(k,f)};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../gift-campaign-aura-engine.js'),'utf8'),c);
 const w={campaignTheme:'gold',giftTarget0:100,giftTarget1:100,giftTarget2:100,giftTarget3:100};
 return{api:c.VyraCampaignAuraEngine,group,w,gifts,listeners,events,media,document,clears:()=>clears,tick(now){for(const f of listeners)f(now)}};
}
test('persistent entry settles, one shared subscription; hidden and detached dispose',()=>{const b=boot();const a=b.api.mount(b.group,b.w);assert.equal(b.listeners.size,1);a.renderAt(8);for(const g of b.gifts){assert.equal(g.style.opacity,1);assert.equal(g.style.transform,'translateX(0px)')}a.renderAt(160);assert.equal(b.gifts[0].style.opacity,1);b.w.hidden=true;b.tick(100);assert.equal(b.listeners.size,0);assert.equal(b.api.active(),0);b.w.hidden=false;b.api.mount(b.group,b.w);b.group.isConnected=false;b.tick(200);assert.equal(b.api.active(),0)});
test('rapid receipts update counters immediately and coalesce after 12 queued events without interrupting',()=>{const b=boot(),a=b.api.mount(b.group,b.w,{manual:true});a.receive(0,1);const start=a.inspect().reactions[0].start;for(let j=0;j<30;j++)a.receive(0,1);assert.equal(a.inspect().values[0],31);assert.equal(a.inspect().queued[0],12);assert.equal(a.inspect().amounts[0],30);assert.equal(a.inspect().reactions[0].start,start);a.renderAt(2.81);assert.equal(a.inspect().queued[0],11);assert.equal(a.inspect().reactions[0].start,2.81);a.receive(1,4,79);assert.equal(a.inspect().values[1],79);assert.equal(a.inspect().values[0],31);a.receive(-1,3);a.receive(0,NaN);assert.equal(a.inspect().values[0],31)});
test('reduced motion and static catalog have no ticker, no reaction queue and show valid goals',()=>{const b=boot(true),a=b.api.mount(b.group,b.w);assert.equal(b.listeners.size,0);a.receive(0,100);assert.equal(a.inspect().queued[0],0);assert.equal(b.gifts[0].querySelector('.goal-mark').textContent,'MÅL KLART');assert.equal(b.gifts[0].querySelector('.frame img').style.transform,'none');b.api.dispose(b.group);const n=boot();n.group.isConnected=false;n.api.still(n.group,n.w);assert.equal(n.api.active(),0);assert.equal(n.listeners.size,0);assert.ok(n.clears()>0)});
test('visibility releases shared clock and resumes without catch-up; session cleanup removes subscriptions',()=>{const b=boot();b.api.mount(b.group,b.w);b.tick(0);b.tick(16);const t=b.api.inspect(b.group).time;b.document.hidden=true;b.events.get('visibilitychange')();assert.equal(b.listeners.size,0);b.document.hidden=false;b.events.get('visibilitychange')();assert.equal(b.listeners.size,1);b.tick(90000);assert.equal(b.api.inspect(b.group).time,t);b.events.get('vyra-session-ended')();assert.equal(b.listeners.size,0);assert.equal(b.api.active(),0)});
test('three aura styles render; targeted receipt does not transform other gifts',()=>{for(const theme of ['gold','platinum','emerald']){const b=boot();b.w.campaignTheme=theme;const a=b.api.mount(b.group,b.w,{manual:true});a.renderAt(4);const other=b.gifts[1].querySelector('.frame img').style.transform;a.receive(0,1);a.renderAt(4);assert.equal(b.gifts[1].querySelector('.frame img').style.transform,other);a.renderAt(4.75);assert.match(b.gifts[0].querySelector('.frame img').style.transform,/rotateY/);a.renderAt(7);assert.doesNotMatch(b.gifts[0].querySelector('.frame img').style.transform,/rotateY/);b.api.dispose(b.group)}});
