'use strict';
const Stripe=require('stripe');
const PLANS={free:{overlays:0,widgets:0,mediaBytes:0,members:1},premium:{overlays:50,widgets:500,mediaBytes:50*1024**3,members:10}};
function stripe(){const key=process.env.STRIPE_SECRET_KEY;if(!key)throw Object.assign(new Error('Betalningar är inte konfigurerade'),{status:503});return new Stripe(key)}
function planFromPrice(price){return price&&price===process.env.STRIPE_PRICE_MONTHLY?'premium':'free'}
// Vad vi laser ur en Stripe-prenumeration. UTBRUTEN UR webhook() for att den ska ga att prova:
// dar inne kravde den bade en databas och en signerad nyttolast, och var darfor otestad.
//
// Uppmatt ur Stripes OpenAPI-spec 2026-08-09: current_period_end finns INTE LANGRE pa
// subscription-objektet — det bor pa subscription_item. Bada lases, sa aldre API-versioner
// fortsatter fungera.
//
// trial_end lases separat och sparas for sig. Periodslutet sammanfaller med provperiodens slut
// under en trial, men bara genom en outtalad slutledning; trial_end ar det falt Stripe
// uttryckligen definierar som "the end of that trial". En nedrakning ska vila pa det.
//
// null, inte 0: fallbacken slutade forr pa 0, vilket blir to_timestamp(0) = 1 januari 1970.
// Kolumnen tillater NULL, och NULL ar det arliga svaret nar vi inte vet.
function prenumerationsfalt(sub){
  const s=sub||{},artikel=s.items&&Array.isArray(s.items.data)?s.items.data[0]:null;
  const tal=v=>Number.isFinite(v)&&v>0?v:null;
  return {
    priceId:(artikel&&artikel.price&&artikel.price.id)||null,
    periodEnd:tal(s.current_period_end)??tal(artikel&&artikel.current_period_end),
    trialEnd:tal(s.trial_end),
  };
}

async function entitlement(pool,workspaceId){const q=await pool.query("SELECT plan,status,current_period_end,trial_end,cancel_at_period_end FROM subscriptions WHERE workspace_id=$1 AND status IN ('active','trialing','past_due')",[workspaceId]),sub=q.rows[0],plan=sub?.plan&&PLANS[sub.plan]?sub.plan:'free';return{plan,limits:PLANS[plan],subscription:sub||null}}
async function usage(pool,workspaceId){const q=await pool.query("SELECT (SELECT count(*)::int FROM overlays WHERE workspace_id=$1) overlays,(SELECT count(*)::int FROM workspace_members WHERE workspace_id=$1) members,(SELECT COALESCE(sum(size_bytes),0)::bigint FROM media_assets WHERE workspace_id=$1 AND status NOT IN ('deleted')) media_bytes",[workspaceId]);return{overlays:q.rows[0].overlays,members:q.rows[0].members,mediaBytes:Number(q.rows[0].media_bytes)}}
async function ensureCustomer(pool,workspaceId,email,name){const existing=await pool.query('SELECT stripe_customer_id FROM billing_customers WHERE workspace_id=$1',[workspaceId]);if(existing.rows[0])return existing.rows[0].stripe_customer_id;const customer=await stripe().customers.create({email,name,metadata:{workspaceId}},{idempotencyKey:`vyra-customer-${workspaceId}`});await pool.query('INSERT INTO billing_customers(workspace_id,stripe_customer_id) VALUES($1,$2) ON CONFLICT(workspace_id) DO NOTHING',[workspaceId,customer.id]);return customer.id}
async function checkout(pool,{workspaceId,email,name,origin}){const price=process.env.STRIPE_PRICE_MONTHLY;if(!price)throw Object.assign(new Error('Månadspriset saknas i serverkonfigurationen'),{status:503});const configured=await stripe().prices.retrieve(price);if(configured.currency!=='usd'||configured.unit_amount!==1500||configured.recurring?.interval!=='month'||configured.recurring?.interval_count!==1)throw Object.assign(new Error('Stripe-priset måste vara exakt 15 USD per månad'),{status:503});const customer=await ensureCustomer(pool,workspaceId,email,name),c=await pool.connect();try{await c.query('BEGIN');const q=await c.query('SELECT trial_started_at FROM billing_customers WHERE workspace_id=$1 FOR UPDATE',[workspaceId]),trialEligible=!q.rows[0]?.trial_started_at,subscription_data={metadata:{workspaceId,plan:'premium'}};if(trialEligible)subscription_data.trial_period_days=3;const session=await stripe().checkout.sessions.create({mode:'subscription',customer,line_items:[{price,quantity:1}],success_url:`${origin}/studio.html?billing=success`,cancel_url:`${origin}/studio.html?billing=cancelled`,client_reference_id:workspaceId,subscription_data,allow_promotion_codes:true},{idempotencyKey:`checkout-${workspaceId}-premium-${Math.floor(Date.now()/300000)}`});if(trialEligible)await c.query('UPDATE billing_customers SET trial_started_at=now() WHERE workspace_id=$1',[workspaceId]);await c.query('COMMIT');return session.url}catch(error){await c.query('ROLLBACK');throw error}finally{c.release()}}
async function portal(pool,workspaceId,origin){const q=await pool.query('SELECT stripe_customer_id FROM billing_customers WHERE workspace_id=$1',[workspaceId]);if(!q.rows[0])throw Object.assign(new Error('Ingen betalningsprofil finns'),{status:404});return(await stripe().billingPortal.sessions.create({customer:q.rows[0].stripe_customer_id,return_url:`${origin}/studio.html?billing=portal`})).url}
async function setCancellation(pool,workspaceId,cancel){const q=await pool.query("SELECT stripe_subscription_id FROM subscriptions WHERE workspace_id=$1 AND status IN ('active','trialing','past_due')",[workspaceId]),id=q.rows[0]?.stripe_subscription_id;if(!id)throw Object.assign(new Error('Inget aktivt abonnemang finns'),{status:404});const sub=await stripe().subscriptions.update(id,{cancel_at_period_end:!!cancel});await pool.query('UPDATE subscriptions SET cancel_at_period_end=$1,updated_at=now() WHERE workspace_id=$2',[!!sub.cancel_at_period_end,workspaceId]);return{cancelAtPeriodEnd:!!sub.cancel_at_period_end,currentPeriodEnd:sub.current_period_end||sub.items?.data?.[0]?.current_period_end||null}}
async function queueBillingNotification(c,event,knownWorkspaceId){const object=event.data.object;let workspaceId=knownWorkspaceId;if(!workspaceId&&object.customer){const q=await c.query('SELECT workspace_id FROM billing_customers WHERE stripe_customer_id=$1',[String(object.customer)]);workspaceId=q.rows[0]?.workspace_id}if(!workspaceId)return;let template;if(event.type==='customer.subscription.created'&&object.status==='trialing')template='trial_started';else if(event.type==='customer.subscription.trial_will_end')template='trial_ending';else if(event.type==='customer.subscription.deleted')template='subscription_ended';else if(event.type==='invoice.paid'&&Number(object.amount_paid||0)>0)template='payment_success';else if(event.type==='invoice.payment_failed')template='payment_failed';else if(event.type==='customer.subscription.updated'&&Object.prototype.hasOwnProperty.call(event.data.previous_attributes||{},'cancel_at_period_end'))template=object.cancel_at_period_end?'cancellation_scheduled':'cancellation_reversed';if(!template)return;await c.query("INSERT INTO notification_outbox(workspace_id,recipient,template,payload,dedupe_key) SELECT w.id,u.email,$2,$3,$4 FROM workspaces w JOIN users u ON u.id=w.owner_user_id WHERE w.id=$1 ON CONFLICT(dedupe_key) DO NOTHING",[workspaceId,template,{stripeEventId:event.id},`${event.id}:${template}`])}
async function webhook(pool,raw,signature){const event=stripe().webhooks.constructEvent(raw,signature,process.env.STRIPE_WEBHOOK_SECRET),c=await pool.connect();try{await c.query('BEGIN');const inserted=await c.query('INSERT INTO billing_events(stripe_event_id,event_type) VALUES($1,$2) ON CONFLICT DO NOTHING RETURNING stripe_event_id',[event.id,event.type]);if(!inserted.rowCount){await c.query('COMMIT');return{duplicate:true,type:event.type}}let workspaceId;if(event.type.startsWith('customer.subscription.')){const sub=event.data.object;workspaceId=sub.metadata?.workspaceId;const {priceId:price,periodEnd,trialEnd}=prenumerationsfalt(sub);if(workspaceId)await c.query("INSERT INTO subscriptions(workspace_id,stripe_subscription_id,stripe_price_id,plan,status,current_period_end,trial_end,cancel_at_period_end,updated_at) VALUES($1,$2,$3,$4,$5,to_timestamp($6),to_timestamp($7),$8,now()) ON CONFLICT(workspace_id) DO UPDATE SET stripe_subscription_id=EXCLUDED.stripe_subscription_id,stripe_price_id=EXCLUDED.stripe_price_id,plan=EXCLUDED.plan,status=EXCLUDED.status,current_period_end=EXCLUDED.current_period_end,trial_end=EXCLUDED.trial_end,cancel_at_period_end=EXCLUDED.cancel_at_period_end,updated_at=now()",[workspaceId,sub.id,price,planFromPrice(price),sub.status,periodEnd,trialEnd,!!sub.cancel_at_period_end])}await queueBillingNotification(c,event,workspaceId);await c.query('COMMIT');return{duplicate:false,type:event.type}}catch(error){await c.query('ROLLBACK');throw error}finally{c.release()}}
module.exports={PLANS,entitlement,usage,checkout,portal,setCancellation,webhook,planFromPrice,prenumerationsfalt};
