'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{release,safeVersion}=require('../desktop-release');
test('desktop releases require an HTTPS installer URL',()=>{assert.throws(()=>release({DESKTOP_DOWNLOAD_URL:'http://example.com/VYRA.exe'}),error=>error.status===503);assert.throws(()=>release({DESKTOP_DOWNLOAD_URL:''}),error=>error.status===503)});
test('desktop release metadata is validated and normalized',()=>{const out=release({DESKTOP_DOWNLOAD_URL:'https://downloads.example/VYRA-Setup.exe',DESKTOP_VERSION:'1.2.3',DESKTOP_SHA256:'A'.repeat(64),DESKTOP_SIZE_BYTES:'2048'});assert.equal(out.version,'1.2.3');assert.equal(out.sha256,'a'.repeat(64));assert.equal(out.sizeBytes,2048);assert.equal(safeVersion(' 1.0.0 '),'1.0.0')});
test('incomplete release metadata is rejected',()=>{assert.throws(()=>release({DESKTOP_DOWNLOAD_URL:'https://downloads.example/VYRA.exe',DESKTOP_VERSION:'1.0.0',DESKTOP_SHA256:'bad',DESKTOP_SIZE_BYTES:'2048'}));assert.throws(()=>release({DESKTOP_DOWNLOAD_URL:'https://downloads.example/VYRA.exe',DESKTOP_VERSION:'',DESKTOP_SHA256:'a'.repeat(64),DESKTOP_SIZE_BYTES:'2048'}));assert.throws(()=>release({DESKTOP_DOWNLOAD_URL:'https://downloads.example/VYRA.exe',DESKTOP_VERSION:'1.0.0',DESKTOP_SHA256:'a'.repeat(64),DESKTOP_SIZE_BYTES:'1'}))});
// Store-länken: frivillig, men ALDRIG godtyckligt. Är variabeln satt ska den peka på Microsofts
// produktsida — annars stoppas den, i stället för att en felskriven länk skickas ut till alla.
const GRUND={DESKTOP_DOWNLOAD_URL:'https://downloads.example/VYRA-Setup.exe',DESKTOP_VERSION:'1.2.4',DESKTOP_SHA256:'a'.repeat(64),DESKTOP_SIZE_BYTES:'2048'};
test('utan DESKTOP_STORE_URL saknas storeUrl helt — .exe-vägen är oförändrad',()=>{const out=release(GRUND);assert.equal('storeUrl' in out,false);assert.equal(out.url,'https://downloads.example/VYRA-Setup.exe');assert.equal(release({...GRUND,DESKTOP_STORE_URL:'   '}).storeUrl,undefined)});
test('DESKTOP_STORE_URL följer med som storeUrl när den pekar på apps.microsoft.com',()=>{const out=release({...GRUND,DESKTOP_STORE_URL:'https://apps.microsoft.com/detail/9PPKZN2SCJM2'});assert.equal(out.storeUrl,'https://apps.microsoft.com/detail/9PPKZN2SCJM2');assert.equal(out.url,'https://downloads.example/VYRA-Setup.exe','302-målet får inte bytas — det är .exe-kanalen');assert.equal(release({...GRUND,DESKTOP_STORE_URL:'https://apps.microsoft.com/detail/9PPKZN2SCJM2?hl=sv-SE&gl=SE'}).storeUrl,'https://apps.microsoft.com/detail/9PPKZN2SCJM2?hl=sv-SE&gl=SE')});
test('en Store-länk som inte är Microsofts produktsida stoppas',()=>{for(const fel of['http://apps.microsoft.com/detail/9PPKZN2SCJM2','https://apps.microsoft.com/','https://apps.microsoft.com/store/detail/9PPKZN2SCJM2','https://example.com/detail/9PPKZN2SCJM2','https://user:pw@apps.microsoft.com/detail/9PPKZN2SCJM2','ms-windows-store://pdp/?productid=9PPKZN2SCJM2','inte en url'])assert.throws(()=>release({...GRUND,DESKTOP_STORE_URL:fel}),error=>error.status===503&&/DESKTOP_STORE_URL/.test(error.message),`skulle stoppats: ${fel}`)});
